### ISSUE TITLE
백업 자동화, S3나 Glacier 라이프사이클 걸기 도입

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#10]
일단 백업용 S3가 생겼다.
https://s3.console.aws.amazon.com/s3/buckets/femiwiki-backups/?region=ap-northeast-1&tab=overview

#### 목표

- 매일 새벽에 작업 실행
- mysqldump로 덤프하여 압축
- S3의 `femiwiki-backups`에 업로드

#### TODOs

- [x] [database](https://github.com/femiwiki/database) Repo의 [auto-backup branch](https://github.com/femiwiki/database/tree/auto-backup) 리뷰 및 머지
- [x] 데이터베이스 서버에서 S3 접근 가능하게 하기(IAM Role 붙이기)
- [x] 데이터베이스 서버에서 git pull 및 bots 스택 디플로이
- [x] 잘 되나 보기(아마 안 될 것임 인생은 그런 것)
  - [x] `docker exec $(docker container ls -qf 'name=bots_backupbot') cat /tmp/log` 로그 확인
  - [x] S3 확인
- [x] 매일 새벽 5시에 자동으로 잘 도는지 확인하기
- [x] Lifecycle Rule로 14일 이상 된 백업들 Glacier로 보내기
- [ ] Glacier로 잘 가는지 확인

#### Activity
- Hyeon Kim added this card to To Do - Sep 6 at 7:03 PM
- Hyeon Kim joined this card - Sep 6 at 7:03 PM
- 낙엽 transferred [this card](https://trello.com/c/hpDWE8Rh) from [FEMIWIKI](https://trello.com/b/zX0oXA4U) - Sep 11 at 2:09 AM

###### Reference
-  https://aws.amazon.com/glacier/

**Comment by simnalamburt** [comment]
[`--single-transaction`](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_single-transaction) 옵션을 반드시 줘야 덤프뜨는동안 서비스가 뻗지 않을것같다.

**Comment by lens0021** [comment]
[이 커밋](https://github.com/femiwiki/backupbot/commit/99e113aaca869af3dcc8d579686b0197974022a5) 서버에 방금 적용해서 그 전까지 2회 시도 실패했습니다 그래서 내일 잘 됐나 확인해 봅니다

**Comment by lens0021** [comment]
> 내일 잘 됐나 확인해 봅니다

S3에 새 파일 없음, 실패 로그: `-bash: swarm: command not found`

**Comment by lens0021** [comment]
https://github.com/femiwiki/backupbot/commit/6995d7b81ee3fde0199fc516b3d319186e2d1c5d 이후 테스트로 돌린 크론에서 실행 잘 되었고 그러나 일단 내일 또 확인해봅니다

**Comment by simnalamburt** [comment]
IAM Role 권한 빠진것도 발견해서 부여했었음

**Comment by lens0021** [comment]
2019-02-07T05:00+09:00로 백업 들어온거 확인했습니다

**Comment by simnalamburt** [comment]
14일 뒤에 Glacier로 가는것 확인하고 닫읍시다

**Comment by lens0021** [comment]
아래 파일들 Storage Class가 Glacier로 바뀌어 있는 것 확인했습니다.

- 2018-09-24T04:09+09:00-mysql-backup.sql.xz
- 2018-09-24T15:00+09:00-femiwiki.com.tar.gz
- 2018-10-07T00:04+09:00-uploaded-files.tar
- 2018-10-07T03:32+09:00-deleted-images.tar
- 2019-02-03T06:53+09:00-mysql-backup.sql.gz
- 2019-02-06T05:00+09:00-mysql-backup.sql.gz
- 2019-02-06T16:47+09:00-mysql-backup.sql.gz
- 2019-02-07T05:00+09:00-mysql-backup.sql.gz

빌링에도 "**Amazon Simple Storage Service APN1-TimedStorage-ByteHrs** $0.025 per GB - first 50 TB / month of storage used" 밑에 "**Amazon Simple Storage Service APN1-TimedStorage-GlacierByteHrs** $0.005 per GB / month of storage used - Amazon Glacier"라고 있는 것 확인했습니다.

이슈 닫습니다.
