### ISSUE TITLE
Parsoid 도커화

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#12]
#### TODO
- [x] 데비안 스트레치 t3.nano로 parsoid 인스턴스 새로 띄우고 caddy 띄우고 설정까지 완료
- [x] 테썹이 새 parsoid 바라보도록 설정하고 정상작동여부 테스트
- [x] 실제서버가 새 parsoid 바라보도록 설정하고 정상작동여부 테스트
- [x] 구 parsoid 종료, 관련 자원들 모두 해제
- [x] parsoid.femiwiki.com DNS 바꿔주기
- [x] 파소이드에 HTTPS 활성화한 뒤, HSTS 켜기
- [x] parsoid 웹서버 caddy로 교체함, HTTPS 인증서 자동갱신 설정 완료
- [x] (별로 중요하지 않아서 안함) 도커 스왐으로 다시 띄운 뒤, 정상작동여부 테스트
- [x] (별로 중요하지 않아서 안함) Packer 써서 Parsoid용 AMI 새로 만들기. 데비안 9에 unattended upgrade 설정한 뒤 도커 깔아주면 됨. (overlay2 쓰는지 체크할것)
- [x] https://github.com/femiwiki/femiwiki.com 에서 parsoid 관련 코드 삭제

#### Activity
- Hyeon Kim added [this card](https://trello.com/c/CKiVVfUa) to To Do - May 14 at 9:22 PM
- Hyeon Kim joined this card - May 14 at 9:22 PM
- Hyeon Kim added TODO to this card - May 14 at 9:23 PM
- 낙엽 transferred this card from [FEMIWIKI](https://trello.com/b/zX0oXA4U) - Sep 11 at 2:08 AM
- Hyeon Kim moved this card from Backlog to Doing - Sep 15 at 7:04 PM
- Hyeon Kim completed 데비안 스트레치 t3.nano로 parsoid 인스턴스 새로 띄우고 caddy 띄우고 설정까지 완료 on this card - Sep 15 at 7:59 PM
- Hyeon Kim completed 테썹이 새 parsoid 바라보도록 설정하고 정상작동여부 테스트 on this card - Sep 15 at 9:05 PM
- Hyeon Kim completed 실제서버가 새 parsoid 바라보도록 설정하고 정상작동여부 테스트 on this card - Sep 15 at 9:05 PM
- Hyeon Kim completed 구 parsoid 종료, 관련 자원들 모두 해제 on this card - Sep 15 at 9:21 PM
- Hyeon Kim completed parsoid.femiwiki.com DNS 바꿔주기 on this card - Sep 15 at 9:21 PM
- Hyeon Kim completed 파소이드에 HTTPS 활성화한 뒤, HSTS 켜기 on this card - Sep 15 at 9:21 PM
- Hyeon Kim completed parsoid 웹서버 caddy로 교체함, HTTPS 인증서 자동갱신 설정 완료 on this card - Sep 15 at 9:22 PM
- Hyeon Kim completed 도커 스왐으로 다시 띄운 뒤, 정상작동여부 테스트 도커스왐은 다음기회에 on this card - Sep 15 at 9:25 PM
- Hyeon Kim completed (별로 중요하지 않아서 안함) Packer 써서 Parsoid용 AMI 새로 만들기. 데비안 9에 unattended upgrade 설정한 뒤 도커 깔아주면 됨. (overlay2 쓰는지 체크할것) on this card - Sep 15 at 9:26 PM
- Hyeon Kim moved this card from Doing to Done - Sep 15 at 9:26 PM
- Hyeon Kim completed femiwiki/femiwiki.com 에서 parsoid 관련 코드 삭제 on this card - Sep 15 at 9:43 PM
- Hyeon Kim moved this card from Done to For Review - Sep 15 at 9:43 PM
- Hyeon Kim marked https://github.com/femiwiki/femiwiki.com 에서 parsoid 관련 코드 삭제 incomplete on this card - Sep 15 at 9:53 PM
- Hyeon Kim moved this card from For Review to Doing - Sep 15 at 9:53 PM
- 낙엽 completed https://github.com/femiwiki/femiwiki.com 에서 parsoid 관련 코드 삭제 on this card - Sep 15 at 10:18 PM
- 낙엽 moved this card from Doing to Done - Sep 15 at 10:18 PM
