### ISSUE TITLE
AWS 보안 관련 제품들 PoC

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#133]
### ✅ Trusted Advisor
원래 쓰고있었음

### ✅ [IAM Access Analyzer](https://aws.amazon.com/iam/features/analyze-access/)
무료여서 바로 실행했고, public accessible한 S3 버킷 두개 나온거 외엔 결과가 없었다. (업로드 파일용 버킷, 이미지 썸네일용 버킷 두개) "Mark as intended" 했다.

### ❌ [Amazon Detective](https://aws.amazon.com/detective/)
2019-12-04에 프리뷰를 신청했고, 2019-12-24에 프리뷰 승낙되었다. 무료로 쓸 수 있다. 써보자.

Update: 별로 유용하지 않아 비활성화했다.

### ❌ [Amazon GuardDuty](https://aws.amazon.com/guardduty/)
CloudTrail 로그, VPC Flow 로그, DNS 로그를 기반으로 위협을 감지하는 서비스다. 30일 free tier 기간동안 무료로 써보고, 비용이 적고 제공해주는 리포트가 유익하다면 계속 켜둘 생각이다.

https://aws.amazon.com/guardduty/pricing/ 처리하는 로그 용량에 비례해 과금된다. 우리같은경우 한달에 대략 23.7만 이벤트, 0.12GB의 로그가 발생하는데 이경우 한달에 약 1.3USD가 과금된다. 제공해주는 정보가 쓸모가 있다면 켤 가치가 있는것같다

Free tier는 2020-01-03에 종료된다.

Update: 누가 tor로 들어온다는 경고가 유일하게 유의미한 경고였고 그 외엔 유용한 리포트를 안줬다. IAM은 정리 안하고 GuardDuty만 Suspend 시켰다. 프리티어 기간 한달간 발생한 비용은 0.01 USD = 11.55원

### ❌ [Amazon Macie](https://aws.amazon.com/macie/)
오레곤 리전에 Macie를 활성화시켰다. Macie는 아래와 같이 S3에 민감한 파일이 실수로 업로드되진 않았는지 검사해주는 서비스다.

![image](https://user-images.githubusercontent.com/4435445/70115042-ca6e6680-16a1-11ea-8934-2474ee5e1934.png)

오레곤과 버지니아 리전에 있는 S3만 검사할 수 있어서 다시 껐다.

### ✅ [Amazon Inspector](https://aws.amazon.com/inspector/pricing/)
VPC 설정과 인스턴스에 취약점이 있는지 검사해준다. 문제는 [Amazon Inspector Agent](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_agents.html)가 켜져있어야 제대로된 결과를 볼 수 있다. 원래 Amazon Linux 2 AMI 엔 기본으로 들어있는데 페미위키에선 미니멀 AMI를 써서 없다.

https://aws.amazon.com/inspector/pricing/ 사용량에 비례해서 과금되는데, 한달 내내 켜놓는 구조가 아니라 하루에 한번, 일주일에 한번, 한달에 한번 등 사용자가 원하는 주기로 실행하는 방식이라 좋은것같다.

페미위키 EC2에 [애드훅하게 설치했고](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_installing-uninstalling-agents.html#install-linux), 예약없이 수동으로 1회 실행했는데 결과가 매우 좋았다.

### ❌ [AWS WAF](https://aws.amazon.com/waf/)
써볼라고했더니 API Gateway나 ALB 안쓰면 못쓴다 다흑

### ❌ [AWS Security Hub](https://aws.amazon.com/security-hub/)
https://aws.amazon.com/security-hub/pricing/ 체크 수에 비례해서 과금된다

1달 프리티어로 써보고있다. Free tier는 2020-01-03에 종료된다. 지금 추세라면 한달에 600원정도 과금될것같다.

Update: AWS Compliance Standard 지키는지 자동으로 검사해주는게 페미위키에선 유일한 효용인데, 자동으로 검사할 필요가 없어보여서 끄기로함. 프리티어기간동안 발생한 비용은 1.12 USD

&nbsp;

## TODOs
- [x] 2020-01-03 에 Amazon GuardDuty 프리티어 종료되었을 때 서비스 비활성화할지 계속 쓸지 결정하기 → Suspend 시켰음
- [x] GuardDuty 정리할때에 IAM Role도 같이 치워야함 → GuardDuty 아예 끄지는 말고 Suspend만 시키기로 해서, IAM Role은 지금처럼 계속 둬야함
- [x] 2020-01-03 에 AWS Security Hub 프리티어 종료되었을 때 서비스 비활성화할지 계속 쓸지 결정하기 → 끔
- [x] SecurityHub 정리할때에 AWS Config도 같이 끈 뒤 config용 S3 버킷 `config-bucket-302617221463` 과 IAM Role, SecurityHub용 IAM Role도 같이 치워야함
- Inspector 결과 보고 고치기 → #186
- [AWS CIS](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards.html) 지키기. 비밀번호 관련된 컴플라이언스는 NIST에서 하지말라는짓은 다하고있어서 쓰레기인데, 그 외는 꽤 괜찮음. → #186

**Comment by simnalamburt** [comment]
AWS Detective가 3월 31일에 GA가 된다고 합니다. 그 전에 꺼야만 합니다.

**Comment by simnalamburt** [comment]
PoC는 끝났고, Amazon Inspector 외엔 유용한게 없었습니다.
