### ISSUE TITLE
AWS 람다 치우기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#14]
뭔가 알수없는 서비스들이 AWS 람다로 돌고있는데, 도커화한 뒤 다른 치우든가 유지하든가 결정하고, 문서화도 적절히 하고 소스관리도 해야함.

#### TODOs
 - [x] fw-api-graphviz : 업데이트하고 문서화하고 라이센스 정리 완료 https://github.com/femiwiki/graphviz-lambda
 - [x] fw-kakaotalk-lambda 고치기
 - [x] 틀:Graphviz 삭제하기 https://femiwiki.com/w/%ED%8B%80:Graphviz
 - [x] 탕수육님에게 연락하여, fw-html2feed fw-kakaotalk-lambda 를 (Apache-2.0 OR MIT) 로 오픈소스해도 되는지 연락하기: 해도 된다고 하셨음
 - [x] fw-kakaotalk-lambda 적절히 사용법 문서화한 뒤 오픈소스하고 치우기
 - [x] fw-html2feed 적절히 사용법 문서화한 뒤 오픈소스하고 치우기

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/rurKNEzQ) to Doing Sep 15 at 1:03 AM
 - Hyeon Kim added TODO to this card Sep 15 at 5:45 AM
 - Hyeon Kim completed fw-api-graphviz : 업데이트하고 문서화하고 라이센스 정리 완료 https://github.com/femiwiki/graphviz-lambda on this card Sep 15 at 6:02 AM
 - Hyeon Kim joined this card Sep 15 at 6:03 AM
 - Hyeon Kim added 낙엽 to this card Sep 15 at 6:03 AM
 - 낙엽 completed 틀:Graphviz 삭제하기 https://femiwiki.com/w/%ED%8B%80:Graphviz on this card Sep 15 at 11:11 AM
 - Hyeon Kim completed 탕수육님에게 연락하여, fw-html2feed fw-kakaotalk-lambda 를 (Apache-2.0 OR MIT) 로 오픈소스해도 되는지 연락하기: 해도 된다고 하셨음 on this card Sep 15 at 1:31 PM
 - Hyeon Kim completed fw-kakaotalk-lambda 고치기 on this card Sep 15 at 1:32 PM
 - Hyeon Kim completed fw-kakaotalk-lambda 적절히 사용법 문서화한 뒤 오픈소스하고 치우기 on this card Sep 15 at 1:55 PM
 - Hyeon Kim completed fw-html2feed 적절히 사용법 문서화한 뒤 오픈소스하고 치우기 on this card Sep 15 at 2:54 PM
 - Hyeon Kim moved this card from Doing to Done Sep 15 at 2:54 PM
