### ISSUE TITLE
Redeploy RESTBase with SQLite as backend

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#149]
https://github.com/femiwiki/docker-restbase/pull/4#issuecomment-570566807 이후 대화 및 개발팀 회의에 나눈 대화를 바탕으로,
[RESTBase를 Cassandra 대신 MySQL을 사용하도록 개변하는 계획](https://github.com/femiwiki/femiwiki/issues/86)을 정지하고 기본 제공되는 SQLite로 사용하도록 하여 다시 구동하려 합니다.
이에 따라 관련 이슈와 PR, repository 등의 정리가 필요합니다.

#### TODOs

- [x] Review https://github.com/femiwiki/docker-restbase/pull/6
- [x] Publish Docker image `femiwiki/restbase:build-2`
- [x] Review https://github.com/femiwiki/docker-mediawiki/pull/340
- [x] Deploy on the server
- [x] Resolve https://github.com/femiwiki/femiwiki/issues/151

#### PRs to close

- [x] https://github.com/femiwiki/restbase-mod-table-mysql/pull/1
- [x] https://github.com/femiwiki/restbase/pull/1
- [x] https://github.com/femiwiki/docker-restbase/pull/4
- [x] https://github.com/femiwiki/docker-mediawiki/pull/289

(branches should be deleted, too)

#### Repos to archive

- [x] [femiwiki/restbase-mod-table-mysql](https://github.com/femiwiki/restbase-mod-table-mysql)
- [x] [femiwiki/restbase](https://github.com/femiwiki/restbase)

**Comment by lens0021** [comment]
[femiwiki/restbase](https://hub.docker.com/r/femiwiki/restbase/) 도커 이미지가 지금 Cassandra를 쓰게 되어 있는데 이걸 갑자기 SQLite를 쓰도록 바꾸면 혹시 다른 도커허브에 안내를 써붙여야 할까요?

**Comment by lens0021** [comment]
> [femiwiki/restbase](https://hub.docker.com/r/femiwiki/restbase/)  도커 이미지가 지금 Cassandra를 쓰게 되어 있는데 이걸 갑자기 SQLite를 쓰도록 바꾸면 혹시 도커허브에 안내를 써붙여야 할까요

*from [Discord](https://discordapp.com/channels/314953743185477644/335014547498729472/663570840100667412)*:

> lens0021: 이거 아마 그냥 바꿔도 될거 같아서 그냥 막 바꿀게요
> simnalamburt: @lens0021 넵
> lens0021: secret.php를 마운트하고 쓸 사람 없겠지 싶고

**Comment by lens0021** [comment]
Repo 둘을 Archive 하게 될 거 같은데 그 안에 있는 PR을 닫고 나서 Archive를 할까요 아니면 닫지 말고 그냥 통째로 Archive해도 상관 없나요? @simnalamburt

**Comment by simnalamburt** [comment]
어느어느레포인가요

**Comment by lens0021** [comment]
- [https://github.com/femiwiki/restbase-mod-table-mysql](https://github.com/femiwiki/restbase-mod-table-mysql)
- [femiwiki/restbase](https://github.com/femiwiki/restbase)
위 두 레포인데, wikimedia/restbase-mod-table-mysql와 사실상 목적이 같아져서 장기적으로도 필요가 없어집니다.

**Comment by simnalamburt** [comment]
그냥 Archive해도 될것같네요

**Comment by lens0021** [comment]
Blocked by https://github.com/femiwiki/femiwiki/issues/151
