### ISSUE TITLE
AWS 서울리전에서 도쿄리전으로 옮기기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#15]
#### TODOs
 - [x] Parsoid (인스턴스, SG)
 - [x] 도쿄리전에 임시로 만든 테스트 서버 AMI 지우기
 - [x] 테스트서버 ENA 활성화하기
 - [x] 테스트서버에 설치한 awscli 지우기
 - [x] 테스트서버 도쿄로 이전
 - [x] 한국리전에 남아있는 구 테스트서버 자원 지우기 (인스턴스, SG, EBS 스냅샷, AMI, EIP)
 - [x] 실서버 ENA 활성화하기
 - [x] 실서버 도쿄로 이전
 - [x] 한국리전에 남아있는 구 실서버 자원 지우기 (인스턴스, SG, EBS 스냅샷, AMI, EIP)
 - [x] 점검풀기 (공지 내리고 편집제한 해제)

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/t0tsJyMz) to Doing Sep 15 at 7:05 PM
 - Hyeon Kim added TODOs to this card Sep 15 at 9:32 PM
 - Hyeon Kim completed Parsoid on this card Sep 15 at 9:32 PM
 - Hyeon Kim completed 도쿄리전에 임시로 만든 테스트 서버 AMI 지우기 on this card Sep 15 at 11:38 PM
 - Hyeon Kim completed 테스트서버에 설치한 awscli 지우기 on this card Sep 16 at 2:15 AM
 - Hyeon Kim completed 테스트서버 ENA 활성화하기 on this card Sep 16 at 2:15 AM
 - Hyeon Kim completed 테스트서버 도쿄로 이전 on this card Sep 16 at 3:37 AM
 - Hyeon Kim completed 한국리전에 남아있는 구 테스트서버 자원 지우기 (인스턴스, SG, EBS 스냅샷, AMI, EIP) on this card Sep 16 at 3:50 AM
 - Hyeon Kim completed 실서버 ENA 활성화하기 on this card Sep 16 at 4:00 AM
 - Hyeon Kim completed 실서버 도쿄로 이전 on this card Sep 16 at 4:58 AM
 - Hyeon Kim completed 한국리전에 남아있는 구 실서버 자원 지우기 (인스턴스, SG, EBS 스냅샷, AMI, EIP) on this card Sep 16 at 4:58 AM
 - 낙엽 completed 점검풀기 (공지 내리고 편집제한 해제) on this card Sep 16 at 5:14 AM
 - 낙엽 moved this card from Doing to Done Sep 16 at 5:14 AM
