### ISSUE TITLE
DB 변화 없는 모든 확장기능 리포 푸시될 때마다 docker-mediawiki 재빌드 시키기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#157]
> Simnalamburt said In https://github.com/femiwiki/femiwiki/issues/69#issuecomment-581119987:
> 
> 확장기능의 경우 푸쉬할때마다 아래와 같이 [repository dispatch](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#external-events-repository_dispatch) API를 호출해서 docker-mediawiki 도커이미지를 재빌드 하는 방식으로 CD를 구현할 예정이다.
> 
> Sanctions는 DB 테이블 구조 변경이 있을 수 있어서 매번 `php update.php`를 실행해줘야하기에 CD 세팅이 쉽지않다.
>
> ```bash
> curl \
>   -XPOST \
>   -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
>   -H "Accept: application/vnd.github.everest-preview+json" \
>   -H "Content-Type: application/json" \
>   https://api.github.com/repos/YOURNAME/APPLICATION_NAME/dispatches \
>   --data '{"event_type": "build_application"}'
> ```

- [x] docker-mediawiki 깃헙 액션으로 확장기능 버전 업 API 추가하기
- [ ]  https://github.com/femiwiki/FemiwikiSkin
- [ ]  https://github.com/femiwiki/UnifiedExtensionForFemiwiki
- [ ]  https://github.com/femiwiki/FacetedCategory
- [ ]  https://github.com/femiwiki/CategoryIntersectionSearch

**Comment by lens0021** [comment]
깃헙 액션에서 `GITHUB_TOKEN`은 자동으로 생성됩니다. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token

**Comment by lens0021** [comment]
여기 assign 해드려도 될까요? @miriryu

**Comment by miriryu** [comment]
**Todo**
DB 변화 없는 모든 확장기능은 다음과 같다.
- [ ]  스킨
- [ ]  Sanctions
- [ ]  UnifiedExtensionForFemiwiki
- [ ]   FacetedCategory
- [ ]   CategoryIntersectionSearch

**Comment by lens0021** [comment]
2019년 11월 기준 답변에 따르면 `repository_dispatch`는 마스터 브랜치에 한해서만 가능하다고 합니다: 
https://github.community/t5/GitHub-API-Development-and/How-to-trigger-repository-dispatch-event-for-non-default-branch/m-p/39559/highlight/true#M3592

**Comment by lens0021** [comment]
이 이슈 대신에 바로 https://github.com/femiwiki/docker-mediawiki/issues/347 진행해보아도 될까요?

https://github.com/femiwiki/docker-mediawiki/blob/8d6dfbe/extension-installer/install_extensions.rb#L104-L110
```ruby
# Extensions developed by Femiwiki team
extensions_femiwiki = [
  'CategoryIntersectionSearch',
  'FacetedCategory',
  'Sanctions',
  'UnifiedExtensionForFemiwiki',
]
```
부분을 고쳐서 릴리즈를 같이 적고 그걸 다운받게 고칠 것 같습니다. @simnalamburt

**Comment by simnalamburt** [comment]
네 좋아여

**Comment by lens0021** [comment]
방향고민중인것 같아 안닫고 놔둡니다.

**Comment by simnalamburt** [comment]
일단은 CD를 하는게 중요하니까 나중에 바꾸더라도 일단은 말씀하셨던대로 확장기능 푸쉬할때마다 extensions.json 을
업데이트하는 방향으로 갈까요

2020년 2월 26일 (수) 12:35, Lens0021 <notifications@github.com>님이 작성:

**Comment by lens0021** [comment]
정리합니다.
1. CD:
    1. docker-mediawiki는 사용중인 non-WMF 확장기능들과 그 버전을 별도 json 파일(가칭 extensions.json)에 모아 관리한다.
    2. 각 플러그인은 push가 있을 시 최신 커밋을 위의 json 파일에 자신의 새 버전으로 갱신한다.
2. Semver: 적절한 때마다 손으로 한다.

여기에서 1.ii는 json을 파싱하여 그 안에서 자기 값을 고치고 다시 이를 json으로 저장하는 일을 해야 하는데 깃헙 액션을 하나 만들어서 도커 컨테이너안에서 해야 결정성이 있을 것 같습니다. 언어는 그냥 통일감있게 루비를 쓸 거 같습니다. 그러면 될까요?

**Comment by lens0021** [comment]
> 깃헙 액션을 하나 만들어서 도커 컨테이너안에서 해야 결정성이 있을 것 같습니다.

이대로 한다면 도커 이미지는 쓰기 읽기 모두 깃헙 액션에서 하는 바 Github Packages 한번 써보게 될 것 같습니다.

**Comment by simnalamburt** [comment]
“각 플러그인은 push가 있을 시 최신 커밋을 위의 json 파일에 자신의 새 버전으로 갱신한다.”를 도커 안에서 하게되면 그 도커를
또 빌드해야하고 그럴텐데 걍 도커 밖에서 하는게 낫지 않을까요 어차피 엄청 짧은 스크립트일거같은데

2020년 2월 26일 (수) 15:20, Lens0021 <notifications@github.com>님이 작성:

**Comment by lens0021** [comment]
짧은 스크립트지만 리포마다 반복해서 써야 해서 고칠 일이 있을 수 있다는 점을 고려하면 하나로 묶는 것이 나을 것 같습니다. 아니면 docker-mediawiki 리포에 스크립트 파일을 만들어서 확장기능에서 curl하고 실행하게 해볼까요?

**Comment by simnalamburt** [comment]
리포마다 반복하지 말고, docker-mediawiki에 API로만 호출할 수 있는 워크플로우 만들고 다른 리포에선 curl로 그거
호출만 하기 이런식으로 하는게 나을거같아요

2020년 2월 26일 (수) 15:34, Lens0021 <notifications@github.com>님이 작성:

**Comment by lens0021** [comment]
악 제가 json한다고 했는데 주석 못다는게 걸려서 yaml로 가능하면 해볼게요

**Comment by simnalamburt** [comment]
그러게요 혹시 yaml이 너무 자유로워서 걸린다면 toml도 좋아요

2020년 2월 26일 (수) 19:14, Lens0021 <notifications@github.com>님이 작성:

**Comment by lens0021** [comment]
https://help.github.com/en/actions/reference/events-that-trigger-workflows:
> An action in a workflow run can't trigger a new workflow run. For example, if an action pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

위와 같은 부분이 있어 액션에서 extensions.json을 고친 이후에는 테스트가 안 돌 가능성이 있습니다. 참고 바랍니다.

**Comment by lens0021** [comment]
테스트를 해봤는데 `GITHUB_TOKEN`으로 repository_dispatch를 하려고 하면 404 Not Found 에러가 나오고\[1], "`public_repo`: Access public repositories" scope가 선택된 personal access token이 있어야 제대로 수행됩니다.

\[1]: https://github.com/lens0021/FemiwikiSkin/actions/runs/46049796/workflow#L18-L33

access token은 @femiwiki-bot 에서 만들면 되겠지만, 토큰을 각 리포에 수동으로 넣기가 번거롭고 원본을 잃어버릴 것 같습니다. 어떻게 할까요?

**Comment by simnalamburt** [comment]
GITHUB_TOKEN이 가진 권한이 제한되어있어서 그러는건지 아니면 잘못 사용해서 그러는건지 궁금하네요.
https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token

GITHUB_TOKEN으로 못하는게 맞다면 별수없이 personal access token을 사용하거나, 아니면 이 접근이 아니라 아예
다른 접근을 쓸 수 밖에 없을것같아요. 아직까진 다른 접근방법은 생각나진 않네요.

**Comment by lens0021** [comment]
실 적용 중 깃헙 액션에 의한 커밋이 보호된 브랜치에 대하여 막혔습니다

> If we enabled GitHub Actions to push to a protected branch then any collaborator in your repo could push any code to any branch they wanted simply by creating a branch and coding the workflow to push to to some other branch.  Using the REST api to merge the PR is the right flow and overtime hopefully there will be actions that make that easier to implement.  
-- https://github.community/t5/GitHub-Actions/Allowing-github-actions-bot-to-push-to-protected-branch/m-p/34454#M1924

**Comment by lens0021** [comment]
PR을 만드는 것으로 대체할까요?

**Comment by simnalamburt** [comment]
이미 만드신거 아니셨나여

**Comment by lens0021** [comment]
브랜치가 보호되어 있어 깃헙 액션이 바로 커밋을 푸시 못 하는 상황입니다. 액션이 PR을 만들도록 고치거나 브랜치의 보호를 풀거나(영원히!) 다른 방법을 찾아야 할 것 같습니다.

**Comment by simnalamburt** [comment]
아 그 이야기였군여

PR을 만드는 방향도 멋지긴 하네요. 근데 확장기능들이 여러번 업데이트된다면 한 PR로 적당히 뭉쳐주는 동작이 필요할텐데, 구현이 약간 까다로울것같네요. 저희가 지금 LocalisationUpdate에 하는것처럼 특정 봇에다가만 푸쉬를 허용하는것은 불가능한가요?

**Comment by lens0021** [comment]
위에 [요 댓글](https://github.com/femiwiki/femiwiki/issues/157#issuecomment-592791287)에서 언급한 문제가 걸리긴 하는데 괜찮으면 그렇게 진행해보고 있겠습니다

**Comment by simnalamburt** [comment]
음 저건 맞는 말이긴 한데 PR 날리는 봇 구현이 좀 까다로울것같긴 해요. 그래도 한번 만들어볼까요? 일단 stateless하게 짜야하고 멱등적으로 동작해야한다는 요구사항이 있고, 여러명이 푸쉬를 동시에 할 수도 있겠네요.

1. femiwiki/FemiwikiSkin 에 아무 푸시가 생긴다면
2. femiwiki/docker-mediawiki 에서 update-extensions 브랜치를 checkout 시도한다
3a. 성공할 경우 다음단계로 진행
3b. 브랜치가 없는 등의 이유로 체크아웃에 실패할 경우, 로컬에서만 master 브랜치와 동일한 위치에 update-extensions 브랜치를 만들고 **리모트에는 아직 푸시하지 않는다**
4. extensions.json 을 고친 뒤 새 커밋을 만들고, 새 커밋을 update-extenions 브랜치에 푸쉬한다. 리모트에 브랜치가 없었을 경우 이 단계에서 자동으로 생성된다
5a. 성공할 경우 다음단계로 진행
5b. 푸쉬가 실패할경우 현재 작업중인 진행상황을 버린 뒤 2번부터 다시시작한다.
6. femiwiki/docker-mediawiki 에 update-extensions 브랜치를 master 브랜치에 머지시키는 PR을 만든다
7a. 성공할 경우 끝
7b. 이미 PR이 있다는 이유로 실패한다면 그대로 에러를 무시하고 정상적으로 종료

이렇게 짜면 데이터 레이스가 있어도 안전할 것 같습니다.

**Comment by lens0021** [comment]
:dizzy_face: 적어주신 플로우를 확인하였습니다. 5-ii에서 다시 2로 돌아가는 부분은 그 사이에 다른 푸시가 있었을 것을 상정한 거로 이해하면 될까요?
다만 6번을 위해 검색해보니 [`actions/create-pull-request`](https://github.com/marketplace/actions/create-pull-request) 액션이 매우 다행스럽게도 다음을 제공하는 것 같습니다:

> 1. Check for repository changes in the Actions workspace. This includes:
>    - untracked (new) files
>    - tracked (modified) files
>    - commits made during the workflow that have not been pushed
> 2. Commit all changes to a new branch, or update an existing pull request branch.
> 3. Create a pull request to merge the new branch into the base—the branch checked out in the workflow.

:tada:

**Comment by simnalamburt** [comment]
> 5-ii에서 다시 2로 돌아가는 부분은 그 사이에 다른 푸시가 있었을 것을 상정한 거로 이해하면 될까요?

넹 https://en.m.wikipedia.org/wiki/Read–modify–write 이거 방지하려구요

2020년 3월 1일 (일) 09:46, Lens0021 <notifications@github.com>님이 작성:
