### ISSUE TITLE
Travis CI 해지하고 GitHub Actions로 대체하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#165]
GitHub Actions로 CI를 통일하자

### TODOs
- [x] https://github.com/femiwiki/docker-mediawiki 의 `.travis.yml`을 GitHub Actions로 대체하기
- [x] https://github.com/femiwiki/FemiwikiSkin 의 `.travis.yml`을 GitHub Actions로 대체하기
- [x] https://github.com/femiwiki/AchievementBadges 의 `.travis.yml`을 GitHub Actions로 대체하기
- [x] https://github.com/femiwiki/oojs-ui/tree/REL1_34 의 `.travis.yml`을 GitHub Actions로 대체하기 https://github.com/femiwiki/oojs-ui/issues/1
- [x] Organization 세팅의 Third-party access에서 Travis CI 막기
- [x] Organization 세팅의 Installed GitHub Apps에서 Travis CI 지우기
- [x] ~~travis-ci.org 에서 페미위키 지우기~~ &rarr; travis-ci.com 으로 옮기면서 이미 없어짐
- [x] ~~travis-ci.com 에서 페미위키 지우기~~ &rarr; 못없앰, 연결은 해제했으니 이대로 괜찮을듯

Travis가 놀랍게도 `.com`과 `.org`가 다른사이트이니 헷갈리지 않도록 주의

**Comment by lens0021** [comment]
제법 진행하였지만 아래 문제가 있었습니다.

>  travis-ci.com 에서 페미위키 지우기

[https://travis-ci.com/organizations/femiwiki/](https://travis-ci.com/organizations/femiwiki/)이나 [https://travis-ci.com/femiwiki](https://travis-ci.com/femiwiki)에서 적절한 메뉴를 찾지 못 했습니다.

>  travis-ci.org 에서 페미위키 지우기

해당 주소에서 제게 페미위키가 표시되지 않습니다.

**Comment by simnalamburt** [comment]
제가 처리할게요

**Comment by simnalamburt** [comment]
Jobs Done
