### ISSUE TITLE
업로드파일 S3에 보관하기 → 포기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#18]
https://github.com/edwardspec/mediawiki-aws-s3/ 이거 낙엽님께서 시도중

#### TODOs
 - [x] `/var/www/femiwiki.com/extensions/AWS` 에 소스코드 체크아웃
 - [x] 컴포저로 종속성 설치함
 - [x] 테스트해보니 안되어서 디버깅중 → 고쳤음
 - [x] AWS 익스텐션 설치하고나니 update.php가 실행이 안됨

#### Activity
 - Hyeon Kim added this card to Doing Sep 23 at 3:23 PM
 - 낙엽 Sep 23 at 4:04 PM (edited) <blockquote>테스트 서버에 AWS extension 설치 완료, Credentials 등 추가 필요하여 LocalSettings.php에서 일시적으로 비활성화함</blockquote>
 - Hyeon Kim added TODOs to this card Sep 23 at 4:26 PM
 - Hyeon Kim completed /var/www/femiwiki.com/extensions/AWS 에 소스코드 체크아웃 on this card Sep 23 at 4:27 PM
 - Hyeon Kim completed 컴포저로 종속성 설치함 on this card Sep 23 at 4:27 PM
 - Hyeon Kim completed 테스트해보니 안되어서 디버깅중 → 고쳤음 on this card Sep 24 at 12:16 AM
 - Hyeon Kim completed AWS 익스텐션 설치하고나니 update.php가 실행이 안됨 on this card Sep 24 at 12:16 AM
 - Hyeon Kim Sep 24 at 12:16 AM <blockquote>이거 하면 너무 S3에 종속적으로 변한다. 특히 S3에 할때랑 로컬에서 운영할때랑 디렉토리 구조가 달라지는게 너무 치명적이다. 일단 포기</blockquote>
 - Hyeon Kim moved this card from Doing to Done Sep 24 at 12:16 AM
 - Hyeon Kim joined this card Sep 24 at 12:55 AM

**Comment by lens0021** [comment]
https://github.com/femiwiki/mediawiki/issues/235 에서 다시 시도하여 성공함
