### ISSUE TITLE
Changing the Instance Type from t3a.micro to t3a.small

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#188]
![image](https://user-images.githubusercontent.com/28209361/77287275-87033b00-6d18-11ea-8196-d8ac2dd7671b.png)

최근(작성 시점) 인스턴스가 위와 같이 Unlimited Mode로 전환되어 있습니다.
(https://github.com/femiwiki/femiwiki/issues/171 와는 다른 양상입니다)

이때 과금액이 아래와 같아서,

> For T2 and T3 instances in Unlimited mode, CPU Credits are charged at:
> 
> **$0.05 per vCPU-Hour** for Linux, RHEL and SLES, and
> $0.096 per vCPU-Hour for Windows and Windows with SQL Web
> --https://aws.amazon.com/ec2/pricing/on-demand/#T2/T3_Unlimited_Mode_Pricing

평소(아래 이미지 참고)에 비해 월등히 높은 편입니다

![image](https://user-images.githubusercontent.com/28209361/77287881-f2014180-6d19-11ea-8ef9-d52b2da59836.png)

또 개발팀 이전 논의에서 인스턴스타입을 t3a.small로 올리는 것은 이미 합의되어 있었으므로(https://github.com/femiwiki/infra/issues/39) 현재 인스턴스 타입도 우선 변경하기로 하였습니다.

----

#### TODO

- [x] 점검 공지하기
- [x] 데이터베이스 백업 확인
- [x] Crate a PR & Terraform plan
- [x] Terraform apply
- [x] 사이트 상태 점검
- [x] 점검 공지 내리기 https://femiwiki.com/index.php?curid=5110&action=edit

#### Reference(s)

- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-resize.html#resize-ebs-backed-instance

**Comment by lens0021** [comment]
@love-adela 님 핑!

**Comment by lens0021** [comment]
![image](https://user-images.githubusercontent.com/28209361/77372791-e0677a80-6da9-11ea-9770-a6c259968cbe.png)

t3a의 베이스라인은 20%이고[1] 위와 같이 Credit 회복 중입니다.

[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-credits-baseline-concepts.html#earning-CPU-credits

**Comment by love-adela** [comment]
고생하셨습니다
