### ISSUE TITLE
ALB 사용하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#19]
#### TODOs
 - [x] femiwiki.com, *.femiwiki.com 인증서 ACM으로 생성함
 - [x] 로드밸런서(ALB) 생성
 - [x] 인증서 자동갱신 가능한지 확인
 - [x] Route53 고쳐서 ALB 통해 유저들이 들어오도록 설정

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/W6w6BrJd) to Doing Sep 23 at 4:06 AM
 - Hyeon Kim added TODOs to this card Sep 23 at 4:07 AM
 - Hyeon Kim completed femiwiki.com, *.femiwiki.com 인증서 ACM으로 생성함 on this card Sep 23 at 4:07 AM
 - Hyeon Kim completed 로드밸런서(ALB) 생성 on this card Sep 24 at 12:21 AM
 - Hyeon Kim completed 인증서 자동갱신 가능한지 확인 on this card Sep 24 at 12:46 AM
 - Hyeon Kim completed Route53 고쳐서 ALB 통해 유저들이 들어오도록 설정 on this card Sep 24 at 12:55 AM
 - Hyeon Kim Sep 24 at 12:55 AM <blockquote>완료</blockquote>
 - Hyeon Kim joined this card Sep 24 at 12:55 AM
 - Hyeon Kim moved this card from Doing to Done Sep 24 at 12:55 AM
