### ISSUE TITLE
Auto scaling 구축

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#2]
[github.com/femiwiki/mediawiki](https://github.com/femiwiki/mediawiki) 를 오토스케일링하도록 하고싶다. 인스턴스 타입은 t3a.nano

### TODOs
- [x] LocalSettings.php 가 이미 존재하면 install.php 가 실행을 멈추는 문제때문에, 오토스케일 망함. 저 문제 먼저 고쳐야함. → https://github.com/femiwiki/mediawiki/pull/223 로 해결
- [x] https://github.com/femiwiki/mediawiki/issues/226 도 해결 필요함
- [ ] `secret.php`을 S3에 업로드(권한 수정 필수) 및 콘테이너에서 동기화가능하게 변경 &rarr; https://github.com/femiwiki/femiwiki/issues/110
- [ ] https://github.com/femiwiki/femiwiki/issues/4
- [ ] t3.micro로 띄워져있는 mediawiki 인스턴스 제거
- [ ] Spot Fleet 적용
- [ ] 뭔진 모르겠지만 처음보는 오토스케일 탭이 하나 더있는데 https://ap-northeast-1.console.aws.amazon.com/awsautoscaling 뭔지 조사하기

**Comment by simnalamburt** [comment]
### Activity
- 낙엽 converted [this card](https://trello.com/c/KVRH6TEs) from a checklist item on [라이트세일 철수](https://trello.com/c/EeVAuDsn) - Dec 21 at 9:54 PM
- 낙엽 added TODOs to this card - Dec 21 at 9:54 PM
- 낙엽 joined this card - Dec 21 at 9:56 PM
- 낙엽 added Hyeon Kim to this card - Dec 21 at 9:56 PM
- Hyeon Kim moved this card from 작업중 to Backlog - Dec 22 at 9:30 PM
- Hyeon Kim moved this card from Backlog to 작업중 - Dec 22 at 9:49 PM
- 낙엽 Dec 23 at 12:03 AM (edited) <blockquote>install.php 스크립트에 '--conf'라는 옵션이 있다는데 뭘 적어도 별 반응도 없고 [install.php](https://phabricator.wikimedia.org/source/mediawiki/browse/REL1_31/maintenance/install.php)과 [CliInstaller.php](https://phabricator.wikimedia.org/source/mediawiki/browse/REL1_31/includes/installer/CliInstaller.php)의 소스코드를 봐도 'conf'가 보이지 않는다. 뭘까???</blockquote>
- 낙엽 Dec 23 at 12:05 AM (edited) <blockquote><p>`php install.php --help`라고 하면 conf 옵션에 대한 설명이 나오는데, 이 설명은 [maintenance.php](https://phabricator.wikimedia.org/source/mediawiki/browse/REL1_31/maintenance/Maintenance.php$510)에서 추가되었다.</p>모르겠어서 질문글 올림<br/> https://www.mediawiki.org/wiki/Topic:Uquw7q00a28p5v42</blockquote>
- Hyeon Kim moved this card from 작업중 to 막힘/리뷰대기중 - Dec 23 at 12:32 AM
- Hyeon Kim completed LocalSettings.php 가 이미 존재하면 install.php 가 실행을 멈추는 문제때문에, 오토스케일 망함. 저 문제 먼저 고쳐야함. → https://github.com/femiwiki/mediawiki/pull/223 로 해결 on this card - Dec 23 at 12:49 AM
- Hyeon Kim completed https://github.com/femiwiki/mediawiki/issues/226 도 해결 필요함 on this card - Dec 24 at 12:43 PM

**Comment by lens0021** [comment]
Declined by https://github.com/femiwiki/femiwiki/issues/117

**Comment by lens0021** [comment]
https://github.com/femiwiki/femiwiki/issues/253 is the newer ticket.
