### ISSUE TITLE
도커 컴포즈 사용하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#20]
#### TODOs
 - [x] 도커 컴포즈 사용법 익힘
 - [x] 파소이드 서버 기존에 있던 도커 컨테이너들 도커 스웜으로 띄움
 - [x] /srv/caddy/config 지우고 /src/caddy/data 를 /src/caddy 로 옮기기

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/41wPphAC) to Doing Sep 24 at 1:04 AM
 - Hyeon Kim added TODOs to this card Sep 24 at 1:53 AM
 - Hyeon Kim completed 도커 컴포즈 사용법 익힘 on this card Sep 24 at 2:27 AM
 - Hyeon Kim completed 도커 스웜으로 띄움 on this card Sep 24 at 2:27 AM
 - Hyeon Kim completed /srv/caddy/config 지우고 /src/caddy/data 를 /src/caddy 로 옮기기 on this card Sep 24 at 2:27 AM
 - Hyeon Kim joined this card Sep 24 at 2:27 AM
 - Hyeon Kim moved this card from Doing to Done Sep 24 at 2:28 AM
