### ISSUE TITLE
페미위키 HTTP 서버 인스턴스 타입, EBS 용량 낮추기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#27]
Femiwiki HTTP 서버를 EC2에서 Lightsail로 이전하기로 결정함. 다시 서울 리전으로 돌아감.

#### TODOs
 - [x] 미디어위키 도커화 마치기
 - [x] [미디어위키 인스턴스]Lightsail에 띄우기(key는 이미 있는 것 사용/이름은 `mediawiki`, 데비안 stretch)
 - [x] [미디어위키 인스턴스]방화벽 설정(22, 80 포트 열기)
 - [x] [미디어위키 인스턴스]도커 설치
 - [x] [미디어위키 인스턴스]스왑메모리 생성(3G)
 - [x] [미디어위키 인스턴스]`git clone https://github.com/femiwiki/mediawiki.git ~/swarm`
 - [x] [미디어위키 인스턴스]env와 secret.php 설정(DB 주소는 private IP 사용)
 - [x] [미디어위키 인스턴스]도커 스웜 생성 및 스택 디플로이(스택 이름은 mediawiki)
 - [x] [Lightsail 로드밸런서]띄우기
 - [x] [Lightsail 로드밸런서]미디어위키 인스턴스로 보내는 리스너 추가
 - [x] [Lightsail 로드밸런서]SSL Certificate 관련 설정하기?? 잘 모르겠음 도와줘요  @simnalamburt 님
 - [x] [Lightsail 로드밸런서]헬스 체크 기본값으로 나뒀더니 에러나서 아무 페이지나 적당히 적었음
 - [x] Lightsail 쪽 페미위키로 접속되는지 확인
 - [x] S3에 위치한 이미지 표시 테스트
 - [x] route53에서 femiwiki.com을 Lightsail 로드밸런서에 연결
 - [x] 파일 업로드 테스트
 - [x] XFF 관련 테스트
 - [x] https://github.com/femiwiki/swarm 에서 Parsoid 관련 부분 제거
 - [x] EC2 로드밸런서 사용량 확인하고 끄기
 - [x] EC2 로드밸런서용 DNS CNAME 삭제
 - [x] https://trello.com/c/PRLaiQ7N
 - [x] EC2 Instance 삭제(Instance, volume, secure group) 이건 젼님 허락맡고해야겠따-낙엽

#### Activity
 - Hyeon Kim added [this card ](https://trello.com/c/nIOQGiIq)to Doing Oct 7 at 12:19 AM
 - Hyeon Kim joined this card Oct 7 at 12:19 AM
 - 낙엽 added 로드밸런서와 미디어위키 Lightsail로 이전 to this card Dec 17 at 3:55 PM
 - 낙엽 joined this card Dec 19 at 5:00 PM
 - 낙엽 completed [미디어위키 인스턴스]Lightsail에 띄우기(key는 이미 있는 것 사용/이름은 mediawiki, 데비안 stretch) on this card Dec 20 at 12:47 AM
 - 낙엽 completed [미디어위키 인스턴스]방화벽 설정(22, 80 포트 열기) on this card Dec 20 at 12:49 AM
 - 낙엽 completed [미디어위키 인스턴스]도커 설치 on this card Dec 20 at 12:52 AM
 - 낙엽 completed [미디어위키 인스턴스]스왑메모리 생성(3G) on this card Dec 20 at 12:52 AM
 - 낙엽 completed [미디어위키 인스턴스]git clone https://github.com/femiwiki/mediawiki.git ~/swarm on this card Dec 20 at 12:56 AM
 - 낙엽 completed [미디어위키 인스턴스]env와 secret.php 설정(DB 주소는 private IP 사용) on this card Dec 20 at 1:00 AM
 - 낙엽 completed [미디어위키 인스턴스]도커 스웜 생성 및 스택 디플로이(스택 이름은 mediawiki) on this card Dec 20 at 1:08 AM
 - 낙엽 completed [Lightsail 로드밸런서]띄우기 on this card Dec 20 at 3:04 AM
 - 낙엽 completed [Lightsail 로드밸런서]미디어위키 인스턴스로 보내는 리스너 추가 on this card Dec 20 at 3:18 AM
 - 낙엽 completed Lightsail 쪽 페미위키로 접속되는지 확인 on this card Dec 20 at 3:18 AM
 - 낙엽 completed S3에 위치한 이미지 표시 테스트 on this card Dec 20 at 3:18 AM
 - 낙엽 completed [Lightsail 로드밸런서]헬스 체크 기본값으로 나뒀더니 에러나서 아무 페이지나 적당히 적었음 on this card Dec 20 at 3:34 AM
 - 낙엽 completed [Lightsail 로드밸런서]SSL Certificate 관련 설정하기?? 잘 모르겠음 도와줘요 @simnalamburt 님 on this card Dec 20 at 4:01 AM
 - 낙엽 completed route53에서 femiwiki.com을 Lightsail 로드밸런서에 연결 on this card Dec 20 at 4:13 AM
 - 낙엽 completed 파일 업로드 테스트 on this card Dec 20 at 4:40 AM
 - 낙엽 Dec 20 at 4:41 AM (edited) <blockquote>파일 업로드 테스트 약간 잘 했는지 불안해서 괜찮으면 몇 번 더 하면 좋겠습니다.</blockquote>
 - 낙엽 completed XFF 관련 테스트 on this card Dec 20 at 4:55 AM
 - 낙엽 completed https://github.com/femiwiki/swarm 에서 Parsoid 관련 부분 제거 on this card Dec 20 at 4:57 AM
 - 낙엽 Dec 21 at 8:40 PM <blockquote>라이트세일의 불안정성(Stolen CPU, 오토스케일링이 없는 LB 등)으로 인해 다시 EC2로 돌아가기로 결정함.</blockquote>
 - 낙엽 moved this card from 작업중 to 완료 Dec 21 at 8:40 PM
 - 낙엽 completed 미디어위키 도커화 마치기 on this card Dec 21 at 8:40 PM
