### ISSUE TITLE
미디어위키 인스턴스 도커 쓰는 새 방식으로 변경

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#29]
지금 미디어위키는 인스턴스 타입도 크고, 도커를 쓰지 않는 옛 방식으로 켜져있다. Femiwiki Base AMI를 써서 새 방식으로 다시 켜주자

#### TODOs
 - [x] 미디어위키 서버용 Launch Template 작성
 - [x] mediawiki 런치템플릿 기반으로 새 mediawiki 인스턴스 생성
 - [x] https://github.com/femiwiki/swarm 에서 미디어위키 띄우는 방법 업데이트
 - [x] parsoid 도커 이미지 빌드 완료될때까지 대기
 - [x] 새 mediawiki 인스턴스에 env, Secret.php 작성
 - [x] 새 mediawiki 인스턴스에 미디어위키 도커 스웜 디플로이
 - [x] 새 mediawiki 인스턴스 정상작동여부 확인
 - [x] 새 mediawiki 인스턴스를 로드밸런서에 붙이기
 - [x] 새 mediawiki 인스턴스에 detailed monitoring 활성화
 - [x] 옛 mediawiki 인스턴스의 '$wgSessionCacheType'을 'CACHE_MEMCACHED'에서 'CACHE_DB'로 수정
 - [x] 페미위키 웹사이트 정상작동 확인
 - [x] 새 mediawiki 인스턴스 detailed monitoring 비활성화
 - [x] 일정 시간동안 새 mediawiki 인스턴스 모니터링: t3.nano 한대가 견디기엔 부하가 많아 크레딧이 유지되지 않음
 - [x] ~~mediawiki용 AMI를 만들어 오토스케일 설정. TODO: Target CPU 5%, Spot Fleet 쓸까? Predictive autoscale 쓸까~~ 오토스케일 망함. 일단 t3.micro 로 띄움
 - [x] 옛 mediawiki 인스턴스를 로드밸런서에서 제거
 - [x] 옛 mediawiki 인스턴스 종료
 - [x] 옛 mediawiki 인스턴스가 쓰던 EBS 제거
 - [x] 옛 mediawiki 인스턴스용 AMI 제거
 - [x] 옛 mediawiki 인스턴스용 EBS 스냅샷 제거

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/QrI3vbjn) to 작업중 Dec 22 at 6:42 PM
 - Hyeon Kim joined this card Dec 22 at 6:42 PM
 - Hyeon Kim added TODOs to this card Dec 22 at 6:43 PM
 - Hyeon Kim completed 미디어위키 서버용 Launch Template 작성 on this card Dec 22 at 6:43 PM
 - Hyeon Kim completed https://github.com/femiwiki/swarm 에서 미디어위키 띄우는 방법 업데이트 on this card Dec 22 at 7:15 PM
 - Hyeon Kim completed mediawiki 런치템플릿 기반으로 새 mediawiki 인스턴스 생성 on this card Dec 22 at 7:16 PM
 - Hyeon Kim completed parsoid 도커 이미지 빌드 완료될때까지 대기 on this card Dec 22 at 7:22 PM
 - Hyeon Kim completed 새 mediawiki 인스턴스에 env, Secret.php 작성 on this card Dec 22 at 7:29 PM
 - Hyeon Kim completed 새 mediawiki 인스턴스에 미디어위키 도커 스웜 디플로이 on this card Dec 22 at 7:29 PM
 - Hyeon Kim completed 새 mediawiki 인스턴스 정상작동여부 확인 on this card Dec 22 at 7:36 PM
 - Hyeon Kim completed 새 mediawiki 인스턴스를 로드밸런서에 붙이기 on this card Dec 22 at 7:36 PM
 - Hyeon Kim completed 새 mediawiki 인스턴스에 detailed monitoring 활성화 on this card Dec 22 at 7:38 PM
 - Hyeon Kim completed 옛 mediawiki 인스턴스의 '$wgSessionCacheType'을 'CACHE_MEMCACHED'에서 'CACHE_DB'로 수정 on this card Dec 22 at 7:44 PM
 - Hyeon Kim completed 일정 시간동안 새 mediawiki 인스턴스 모니터링: 수정이 잦을 때 CPU 사용이 많음 on this card Dec 22 at 7:57 PM
 - Hyeon Kim completed 옛 mediawiki 인스턴스를 로드밸런서에서 제거 on this card Dec 22 at 7:57 PM
 - Hyeon Kim marked 일정 시간동안 새 mediawiki 인스턴스 모니터링: 수정이 잦을 때 CPU 사용이 많음 incomplete on this card Dec 22 at 7:57 PM
 - Hyeon Kim completed 페미위키 웹사이트 정상작동 확인 on this card Dec 22 at 8:04 PM
 - Hyeon Kim marked 옛 mediawiki 인스턴스를 로드밸런서에서 제거 incomplete on this card Dec 22 at 8:18 PM
 - Hyeon Kim completed 새 mediawiki 인스턴스 detailed monitoring 비활성화 on this card Dec 22 at 8:37 PM
 - Hyeon Kim completed 일정 시간동안 새 mediawiki 인스턴스 모니터링: t3.nano 한대가 견디기엔 부하가 많아 크레딧이 유지되지 않음 on this card Dec 22 at 8:37 PM
 - Hyeon Kim completed mediawiki용 AMI를 만들어 오토스케일 설정. TODO: Target CPU 5%, Spot Fleet 쓸까? Predictive autoscale 쓸까 오토스케일 망함. 일단 t3.micro 로 띄움 on this card Dec 22 at 9:16 PM
 - Hyeon Kim completed 옛 mediawiki 인스턴스를 로드밸런서에서 제거 on this card Dec 22 at 9:20 PM
 - Hyeon Kim completed 옛 mediawiki 인스턴스 종료 on this card Dec 22 at 9:25 PM
 - Hyeon Kim completed 옛 mediawiki 인스턴스가 쓰던 EBS 제거 on this card Dec 22 at 9:25 PM
 - Hyeon Kim completed 옛 mediawiki 인스턴스용 AMI 제거 on this card Dec 22 at 9:26 PM
 - Hyeon Kim completed 옛 mediawiki 인스턴스용 EBS 스냅샷 제거 on this card Dec 22 at 9:27 PM
 - Hyeon Kim moved this card from 작업중 to 완료 Dec 22 at 9:27 PM
