### ISSUE TITLE
서버간 통신에 외부망 사용하는 부분 모두 없애기!

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#30]
#### TODOs
 - [x] 미디어위키가 디비를 내부망 통해 접근하도록 수정하기
 - [x] 라이트세일 'database' 서버에 떠있는 Parsoid 삭제하기
 - [x] 디비가 3306포트를 외부에 열지 않도록 수정

#### Activity
 - 김메잊이 added [this card](https://trello.com/c/PRLaiQ7N) to Backlog Dec 16 at 12:42 AM
 - 낙엽 added TODOs to this card Dec 16 at 2:35 AM
 - 낙엽 Dec 16 at 7:24 PM <blockquote>EC2에서 lightsail로 넘어가는 도중에, EC2는 도쿄에, lightsail는 서울에 위치하면서 둘 사이를 VPC peering으로 연결하려는 시도가 실패함. 이에 따라 일시적으로 외부망을 타게 처리함.</blockquote>
 - 낙엽 moved this card from Backlog to 작업중 Dec 20 at 12:33 PM
 - Hyeon Kim completed 미디어위키가 디비를 내부망 통해 접근하도록 수정하기 on this card Dec 20 at 12:34 PM
 - 낙엽 moved this card from 작업중 to Backlog Dec 20 at 12:50 PM
 - 낙엽 moved this card from Backlog to 작업중 Dec 20 at 1:46 PM
 - Hyeon Kim completed 라이트세일 'database' 서버에 떠있는 Parsoid 삭제하기 on this card Dec 22 at 9:30 PM
 - Hyeon Kim completed 디비가 3306포트를 외부에 열지 않도록 수정 on this card Dec 22 at 9:30 PM
 - Hyeon Kim Dec 22 at 9:30 PM <blockquote>라이트세일을 버리면서 자연스럽게 해결됨</blockquote>
 - Hyeon Kim moved this card from 작업중 to 완료 Dec 22 at 9:31 PM
