### ISSUE TITLE
라이트세일 철수

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#31]
#### TODOs
 - [x] (Lightsail)mediawiki Instance에서 secret 등 의미 있는 파일 백업
 - [x] (Lightsail)mediawiki Instance 제거
 - [x] (Lightsail)Load Balancer 제거
 - [x] (Route 53)Lightsail 인증서를 위해 등록한 CNAME 삭제
 - [x] MySQL Docker Image 버전 확인(=싸그리 압축해서 이동하는 게 아직도 먹히는지 확인) / 기존 MySQL: Ver 8.0.13 for Linux on x86_64 (MySQL Community Server - GPL) 현재 docker image: 8.0.13
 - [x] Femiwiki Base AMI 만듦 https://github.com/femiwiki/femiwiki/issues/28
 - [x] (EC2)t3.nano Instance 'database' 생성(Amazon Linux 2)
 - [x] (EC2 database Instance)보안그룹 설정
 - [x] (EC2 database Instance)[뭔가 고정되는 private IP 붙이기](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/MultipleIP.html)
 - [x] (EC2 database Instance)[도커 설치](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html#install_docker)
 - [x] (EC2 database Instance)스왑메모리 생성
 - [x] (EC2 database Instance)git pull femiwki/swarm
 - [x] Lightsail database Instance에 EC2를 위한 pem 전송
 - [x] Lightsail 인스턴스 ssh 보안 그룹에 추가
 - [x] (EC2)**t3.small femiwiki.com LocalSettingsSecure.php에서 데이터베이스 잠금**
 - [x] (Lightsail database Instance)`/srv/mysql` 디렉토리 tar
 - [x] (Lightsail database Instance)tar 파일 EC2 database Instance로 전송
 - [x] (EC2 database Instance)tar 파일 압축 풀고 적절한 곳에 위치시키기
 - [x] (EC2 database Instance)`chown -R root:roor`, `chmod 700`
 - [x] (Lightsail database Instance)`~/swarm/secret` 파일도 같이 이동
 - [x] (EC2 database Instance)도커 스택 디플로이(database)
 - [x] (EC2)t3.small femiwiki.com LocalSettingsSecure.php DB 주소 변경
 - [x] (EC2)**t3.small femiwiki.com LocalSettingsSecure.php에서 데이터베이스 잠금 해제**
 - [x] (EC2 database Instance)도커 스택 디플로이(bots)
 - [x] (Lightsail database Instance)bots service 정지
 - [x] (Lightsail database Instance)pem 파일 삭제
 - [x] https://github.com/femiwiki/femiwiki/issues/29 완료하기
 - [x] (Lightsail)database Instance 제거
 - [x] (Lightsail)snapshot 전부 삭제
 - [x] (Lightsail)뭐 남은거 있나 살펴보기
 - [x] EC2 mediawiki-old Instance에서 Elastic IP 떼기
 - [x] ssh 보안 그룹에서 Lightsail 인스턴스 제거
 - [x] DEBUG 보안 그룹 Inbound 삭제
 - [x] IAM 계정에서 femiwiki-lightsail 삭제
 - [x] (Lightsail)청구되는 요금 있는지 체크

#### Activity
 - 낙엽 added [this card](https://trello.com/c/EeVAuDsn) to 작업중 Dec 21 at 8:46 PM
 - 낙엽 added TODOs to this card Dec 21 at 8:51 PM
 - 낙엽 completed --------------------------------------------------------------------------- on this card Dec 21 at 8:56 PM
 - 낙엽 converted Auto scaling 구축 from a checklist item on this card Dec 21 at 9:54 PM
 - 낙엽 joined this card Dec 21 at 9:56 PM
 - 낙엽 added Hyeon Kim to this card Dec 21 at 9:56 PM
 - 낙엽 completed (Lightsail)Load Balancer 제거 on this card Dec 21 at 10:53 PM
 - 낙엽 completed (Route 53)Lightsail 인증서를 위해 등록한 CNAME 삭제 on this card Dec 21 at 10:53 PM
 - 낙엽 completed MySQL Docker Image 버전 확인(=싸그리 압축해서 이동하는 게 아직도 먹히는지 확인) / 기존 MySQL: Ver 8.0.13 for Linux on x86_64 (MySQL Community Server - GPL) on this card Dec 21 at 11:17 PM
 - 낙엽 completed (Lightsail)mediawiki Instance에서 secret.php 등 의미 있는 파일 백업 on this card Dec 22 at 12:39 AM
 - 낙엽 completed (Lightsail)mediawiki Instance 제거 on this card Dec 22 at 12:41 AM
 - 낙엽 completed (EC2)t3.nano Instance 'database' 생성(Amazon Linux 2) on this card Dec 22 at 1:56 AM
 - 낙엽 completed (EC2 database Instance)보안그룹 설정 on this card Dec 22 at 2:07 AM
 - Hyeon Kim completed (EC2 database Instance)뭔가 고정되는 private IP 붙이기 on this card Dec 22 at 2:43 AM
 - Hyeon Kim completed (EC2 database Instance)도커 설치 on this card Dec 22 at 3:30 AM
 - Hyeon Kim completed (EC2 database Instance)스왑메모리 생성 on this card Dec 22 at 3:30 AM
 - Hyeon Kim completed (EC2 database Instance)git pull femiwki/swarm on this card Dec 22 at 3:35 AM
 - Hyeon Kim completed (EC2 database Instance)git checkout 43dac0af5f0a6907e790557755cdda234e6b5899로 parsoid가 포함된 commit으로 변경 on this card Dec 22 at 3:36 AM
 - 낙엽 completed Lightsail database Instance에 EC2를 위한 pem 전송 on this card Dec 22 at 3:40 AM
 - 낙엽 completed (EC2)t3.small femiwiki.com LocalSettingsSecure.php에서 데이터베이스 잠금 on this card Dec 22 at 3:42 AM
 - 낙엽 completed (Lightsail database Instance)/srv/mysql 디렉토리 tar on this card Dec 22 at 3:48 AM
 - 낙엽 completed Lightsail 인스턴스 ssh 보안 그룹에 추가 on this card Dec 22 at 3:59 AM
 - 낙엽 completed (Lightsail database Instance)tar 파일 EC2 database Instance로 전송 on this card Dec 22 at 3:59 AM
 - 낙엽 completed (EC2 database Instance)tar 파일 압축 풀고 적절한 곳에 위치시키기 on this card Dec 22 at 4:05 AM
 - 낙엽 completed (Lightsail database Instance)~/swram/secret 파일도 같이 이동 on this card Dec 22 at 4:07 AM
 - 낙엽 completed (Lightsail database Instance)bots service 정지 on this card Dec 22 at 4:09 AM
 - 낙엽 marked (Lightsail database Instance)bots service 정지 incomplete on this card Dec 22 at 1:09 PM
 - 낙엽 completed (EC2 database Instance)chown -R root:roor, chmod 700 on this card Dec 22 at 3:21 PM
 - 낙엽 marked (Lightsail database Instance)~/swram/secret 파일도 같이 이동 incomplete on this card Dec 22 at 3:21 PM
 - Hyeon Kim archived this card Dec 22 at 6:27 PM
 - Hyeon Kim sent this card to the board Dec 22 at 6:27 PM
 - Hyeon Kim completed (Lightsail database Instance)~/swarm/secret 파일도 같이 이동 on this card Dec 22 at 6:30 PM
 - Hyeon Kim completed Femiwiki Base AMI 만듦 https://github.com/femiwiki/femiwiki/issues/28 on this card Dec 22 at 6:30 PM
 - 낙엽 completed (EC2 database Instance)도커 스택 디플로이(database) on this card Dec 22 at 6:33 PM
 - 낙엽 completed (EC2)t3.small femiwiki.com LocalSettingsSecure.php DB 주소 변경 on this card Dec 22 at 6:35 PM
 - 낙엽 completed (EC2)t3.small femiwiki.com LocalSettingsSecure.php에서 데이터베이스 잠금 해제 on this card Dec 22 at 6:35 PM
 - 낙엽 completed (Lightsail database Instance)bots service 정지 on this card Dec 22 at 6:48 PM
 - 낙엽 completed (EC2 database Instance)도커 스택 디플로이(bots) on this card Dec 22 at 6:48 PM
 - Hyeon Kim completed (Lightsail database Instance)pem 파일 삭제 on this card Dec 22 at 6:54 PM
 - Hyeon Kim completed https://github.com/femiwiki/femiwiki/issues/29 완료하기 on this card Dec 22 at 9:27 PM
 - Hyeon Kim completed (Lightsail)database Instance 제거 on this card Dec 22 at 9:28 PM
 - Hyeon Kim completed (Lightsail)snapshot 전부 삭제 on this card Dec 22 at 9:29 PM
 - Hyeon Kim completed (Lightsail)뭐 남은거 있나 살펴보기 on this card Dec 22 at 9:29 PM
 - Hyeon Kim completed EC2 mediawiki-old Instance에서 Elastic IP 떼기 on this card Dec 22 at 9:29 PM
 - Hyeon Kim completed ssh 보안 그룹에서 Lightsail 인스턴스 제거 on this card Dec 22 at 9:29 PM
 - Hyeon Kim completed DEBUG 보안 그룹 Inbound 삭제 on this card Dec 22 at 9:29 PM
 - Hyeon Kim completed IAM 계정에서 femiwiki-lightsail 삭제 on this card Dec 22 at 9:30 PM
 - Hyeon Kim completed (Lightsail)청구되는 요금 있는지 체크 on this card Dec 22 at 9:40 PM
 - Hyeon Kim moved this card from 작업중 to 완료 Dec 22 at 9:40 PM

**Comment by lens0021** [comment]
라이트세일 철수했던 이유는 다음과 같습니다.<sup>[[1]](https://discordapp.com/channels/314953743185477644/566264019409698817/632537585163698196)</sup>

- t3가 아니라 t2라서 ENA 지원 안되어서 인터넷 느림
- 자꾸 이웃이 CPU 스틸해감(아래에서 설명)
