### ISSUE TITLE
서버 비용 절감

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#32]
선택지가 많다.

1. 전부 버리고 GCP 프리티어로 이사
2. Azure 프리티어로 이사
3. 이메일 바꾼 뒤, 새 AWS 프리티어로 이사
4. ~~AWS Lightsail로 이사~~ 이동( https://github.com/femiwiki/femiwiki/issues/27 )후 철수( https://github.com/femiwiki/femiwiki/issues/31 )함

#### Todos
- [x] [일단 도쿄리전으로 이사](https://github.com/femiwiki/femiwiki/issues/15)
- [x] ~~테스트서버 스팟 인스턴스로 띄워서 비용 절감~~ &rarr; 테스트서버 끄기
- [x] 불필요한 자원 안떠있나 확인 https://resources.console.aws.amazon.com/r/tags &rarr; 확인 완료
- [x] LB 쓰지 않기 → https://github.com/femiwiki/femiwiki/issues/93
- [x] EC2 인스턴스 타입 T3a 로 변경 &rarr; https://github.com/femiwiki/femiwiki/issues/87
- [x] 볼륨 타입 standard와 gp2일 때 요금 차이 비교 후 변경 &rarr; https://github.com/femiwiki/femiwiki/issues/125
- [x] EC2 인스턴스 하나로 줄이기 &rarr; https://github.com/femiwiki/femiwiki/issues/117
- [x] AWS에 RI 걸기 &rarr; https://github.com/femiwiki/femiwiki/issues/92
- 그 다음 방향 고민하기

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/RatcUQ7g) to To Do - Sep 6 at 7:05 PM
 - Hyeon Kim joined this card - Sep 6 at 7:06 PM
 - Hyeon Kim added 절차 to this card - Sep 6 at 7:07 PM
 - 낙엽 transferred this card from [FEMIWIKI](https://trello.com/b/zX0oXA4U) - Sep 11 at 2:09 AM
 - Hyeon Kim removed 절차 from this card - Sep 15 at 1:03 AM
 - Hyeon Kim moved this card from Backlog to Doing - Sep 15 at 1:03 AM
 - Hyeon Kim moved this card from Doing to Backlog - Sep 15 at 1:20 AM
 - Hyeon Kim added TODOs to this card - Sep 16 at 5:17 AM
 - Hyeon Kim completed 일단 도쿄리전으로 이사 on this card - Sep 16 at 5:17 AM
 - Hyeon Kim completed 테스트서버 스팟 인스턴스로 띄워서 비용 절감 on this card - Sep 16 at 5:18 AM
 - Hyeon Kim moved this card from Backlog to Doing - Sep 16 at 5:29 AM
 - Hyeon Kim moved this card from Doing to Backlog - Sep 19 at 6:28 PM

**Comment by simnalamburt** [comment]
https://resources.console.aws.amazon.com/r/tags 이 페이지에 들어가서 아래와 같이 검색을 하면 AWS에 떠있는 모든 자원을 볼 수 있다. 대부분은 기본생성된 자원들이라 걸러서 봐야한다.

![1](https://user-images.githubusercontent.com/4435445/52164961-44aa2380-273d-11e9-841c-ab3b1f89ed8b.png)
