### ISSUE TITLE
트윗봇&랭킹봇 봇 패스워드 사용

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#35]
#### Todos
 - [x] https://github.com/femiwiki/tweetbot/blob/master/tweetbot/tweet.py#L67 고치기(미리 해놔도 골뱅이 뒤는 적당히 무시되는지 괜찮아서 미리 해놓음)
 - [x] 사용자:트윗봇으로 로그인하여 [[특수:봇비밀번호]]로 비밀번호 발급받기
 - [x] 랭킹봇 봇 패스워드 발급받기
 - [x] 봇 서버의 `~/swarm/secret' 파일 안에 있는 있는 트윗봇 비밀번호 고치기
 - [x] 봇 서버의 `~/swarm/secret' 파일 안에 있는 있는 랭킹봇 비밀번호 고치기
 - [ ] 잘 되나 확인하기

#### Activity
 - 낙엽 added [this card](https://trello.com/c/K9irkrnH) to Backlog - Nov 4 at 1:02 AM
 - 낙엽 joined this card - Nov 4 at 1:02 AM
 - 낙엽 added Checklist to this card - Nov 18 at 9:18 PM
 - 낙엽 completed https://github.com/femiwiki/tweetbot/blob/master/tweetbot/tweet.py#L67 고치기(미리 해놔도 골뱅이 뒤는 적당히 무시되는지 괜찮아서 미리 해놓음) on this card - Nov 18 at 9:22 PM
 - 낙엽 Dec 16 at 5:54 PM <blockquote>봇 기본 비밀번호 보관</blockquote>

**Comment by lens0021** [comment]
트윗 잘 되었습니다
