### ISSUE TITLE
DB를 독립된 인스턴스로 분리하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#38]
디비 인스턴스 독립 겸, 디비 업그레이드. MariaDB 10.1 → MySQL 8.0
디비 비밀번호도 드디어 root가 아니라 제대로된 비밀번호가 생김

#### TODOs
- [x] 공지띄우기
- [x] DB 잠금
- [x] 프로덕션 DB 백업하기
- [x] 파소이드 서버에 MySQL 8.0 띄움
- [x] 파소이드 서버에 램이 너무 없어서, DB 띄우면 문제될것같아서 파소이드 좀더 큰 인스턴스로 옮김
- [x] 파소이드 서버에 디비 복구
- [x] 파소이드 서버에 임시로 설치한 mysql client 지우기. `sudo apt-get autoremove mysql-common mysql-community-client mysql-community-client-core`
- [x] 실서버에 임시로 설치한 mysql-client 지우기
- [x] 정상작동 확인

#### Activity
- Hyeon Kim added [this card](https://trello.com/c/1Mp8C218) to Doing - Sep 24, 2018 at 12:57 AM
- Hyeon Kim added TODOs to this card - Sep 24, 2018 at 12:58 AM
- 낙엽 completed 공지띄우기 on this card - Sep 24, 2018 at 1:25 AM
- Hyeon Kim completed DB 잠금 on this card - Sep 24, 2018 at 4:33 AM
- Hyeon Kim completed 프로덕션 DB 백업하기 on this card - Sep 24, 2018 at 4:33 AM
- Hyeon Kim completed 파소이드 서버에 MySQL 8.0 띄움 on this card - Sep 24, 2018 at 4:33 AM
- Hyeon Kim completed 파소이드 서버에 램이 너무 없어서, DB 띄우면 문제될것같아서 파소이드 좀더 큰 인스턴스로 옮김 on this card - Sep 24, 2018 at 4:33 AM
- Hyeon Kim completed 파소이드 서버에 디비 복구 on this card - Sep 24, 2018 at 6:33 AM
- Hyeon Kim completed 실서버에 임시로 설치한 mysql-client 지우기 on this card - Sep 24, 2018 at 7:38 AM
- Hyeon Kim completed 파소이드 서버에 임시로 설치한 mysql client 지우기. sudo apt-get autoremove mysql-common mysql-community-client mysql-community-client-core on this card - Sep 24, 2018 at 7:40 AM
- Hyeon Kim completed 정상작동 확인 on this card - Sep 24, 2018 at 7:40 AM
- Hyeon Kim moved this card from Doing to Done - Sep 24, 2018 at 7:40 AM
