### ISSUE TITLE
Continuous Delivery

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#4]
### TODOs
- [x] 도커화
- [x] CI 도입 https://github.com/femiwiki/femiwiki/issues/5
- [x] 자동으로 태그가 붙은 도커 이미지가 repo에 푸쉬되어야함 &rarr; https://github.com/femiwiki/femiwiki/issues/56
- [x] [Docker Hub 대신 GitHub Packages 사용](https://github.com/femiwiki/femiwiki/issues/97)
- [x] Docker Swarm을 Nomad로 대체 https://github.com/femiwiki/femiwiki/issues/116
- [x] 배포 자동화
- [x] Revert https://github.com/femiwiki/infra/issues/59

### Activity
- Hyeon Kim added [this card](https://trello.com/c/oTpLyv2n) to Backlog - Dec 24 at 12:38 PM
- Hyeon Kim added TODOs to this card - Dec 24 at 12:39 PM
- Hyeon Kim completed 도커화 on this card - Dec 24 at 12:39 PM

**Comment by simnalamburt** [comment]
AWS CodeDeploy 버리고

깃헙액션과 깃헙레지스트리가 나왔으니 도커 이미지 CI는 그 둘로 하면 될거같고

쿠버로 옮기고있으니 배포도 깃헙액션에서 진행할 수 있게되었다.

GitHub Actions로 실행하고
Github Registry를 도커 리포로 쓰고
Helm + Kustomize 로 YAML 배포하고
시크릿은 https://github.com/bitnami-labs/sealed-secrets 로 관리하면

편하고 깔끔한 GitOps가 완성된다

**Comment by lens0021** [comment]
Nomad 작업 진행 중 시도해보았으나 다음과 같이 실패했습니다.

```
Placement Failure
Task Group "fastcgi":
  * Resources exhausted on 1 nodes
  * Dimension "memory" exhausted on 1 nodes

Task Group "http":
  * Resources exhausted on 1 nodes
  * Dimension "network: reserved port collision http=80" exhausted on 1 nodes
```

사용한 update 블록 (https://github.com/femiwiki/nomad/commit/ae9075498fb1a1e93d3d018cb6c7f0fc699af45a)
```hcl
# The update stanza specified at the job level will apply to all groups within the job
update {
  max_parallel = 1
  health_check = "checks"
  auto_revert  = false
  auto_promote = true
  # canary count equal to the desired count allows a Nomad job to model blue/green deployments
  canary       = 1
}
```
