### ISSUE TITLE
AWS 관련

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#42]
카드 여러개로 쪼갬

#### 세부

- [x] MFA가 있는 유저만 어드민 액세스를 갖고, MFA가 없으면 읽기전용으로 너프시키기 -> https://github.com/femiwiki/femiwiki/issues/23 로 이동
- [x] Vault SSH 도입 -> https://github.com/femiwiki/femiwiki/issues/9 로 이동
- [x] AWS Glacier로 백업 도입 -> https://github.com/femiwiki/femiwiki/issues/10 로 이동

#### Activity

- 낙엽 added [this card](https://trello.com/c/00msmOyS) to To Do - Apr 19, 2018 at 8:20 AM
- 낙엽 added 세부 to this card - Apr 19, 2018 at 8:21 AM
- 낙엽 added 김지현 to this card - Apr 19, 2018 at 8:30 AM
- 낙엽 joined this card - Apr 19, 2018 at 8:30 AM
- 낙엽 added Hyeon Kim to this card - Apr 19, 2018 at 3:52 PM
- 낙엽 added Choi Damdam to this card - Apr 20, 2018 at 11:39 AM
 - 낙엽 Apr 21, 2018 at 10:15 AM <blockquote>"mysql의 데이터 디렉터리, mediawiki의 images 디렉터리 등 일부만 mounted volume으로 컨테이너 외부로 빼놓으면, 해당 디렉터리만 압축하면 백업이 되고 복구 또한 쉽게 됩니다. 역시나 구글 드라이브 파일을 참고해주세요."라고 탕수육님 이메일에 적혀 있어서 옮겨 적습니다.</blockquote>
- Hyeon Kim completed MFA가 있는 유저만 어드민 액세스를 갖고, MFA가 없으면 읽기전용으로 너프시키기 on this card - Sep 6, 2018 at 7:02 PM
- Hyeon Kim completed Vault SSH 도입 on this card - Sep 6, 2018 at 7:03 PM
- Hyeon Kim completed AWS Glacier로 백업 도입 on this card - Sep 6, 2018 at 7:03 PM
- 낙엽 transferred this card from [FEMIWIKI](https://trello.com/b/zX0oXA4U) - Sep 11, 2018 at 2:13 AM
