### ISSUE TITLE
로드밸런서 제거하기 → 제거 안하기로 결정

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#43]
~~현재 오토스케일이 불가능한 상태임. 비용절약을 위해 무의미한 로드밸런서는 제거하자.~~ TLS 인증서때문에 로드밸런서 제거하면 안됨.

로드밸런서 없이 HTTPS 사용이 불가한것은 아니나 작업이 많이 필요하고 나중에 급하게 서버를 추가하는것이 불가능해짐

#### TODOs

- [x] mediawiki 서버에 EIP 부여
- [x] route53 에서 femiwiki.com 변경
- [x] ~~로드밸런서에 더이상 요청 들어오지 않는것 확인~~
- [x] 로드밸런서 삭제

#### Activity

- Hyeon Kim added [this card](https://trello.com/c/kV547cy9) to 작업중 - Dec 22, 2018 at 9:45 PM
- Hyeon Kim added TODOs to this card - Dec 22, 2018 at 9:45 PM
- Hyeon Kim completed mediawiki 서버에 EIP 부여 on this card - Dec 22, 2018 at 9:46 PM
- Hyeon Kim completed route53 에서 femiwiki.com 변경 on this card - Dec 22, 2018 at 9:47 PM
- Hyeon Kim completed 로드밸런서에 더이상 요청 들어오지 않는것 확인 on this card - Dec 22, 2018 at 9:51 PM
- Hyeon Kim completed 로드밸런서 삭제 on this card - Dec 22, 2018 at 9:52 PM
- Hyeon Kim moved this card from 작업중 to 막힘/리뷰대기중 - Dec 22, 2018 at 9:52 PM
- Hyeon Kim moved this card from 막힘/리뷰대기중 to 완료 - Dec 22, 2018 at 9:52 PM
