### ISSUE TITLE
OOUI 테마 제작

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#46]
_Copied from original issue: femiwiki/femiwiki.com#119_<br>
_From @lens0021 on April 30, 2018 2:46_

https://github.com/femiwiki/mediawiki/issues/93 관련 
> OOUI implements a "WikimediaUI" theme – conforming to Wikimedia Foundation's user interface style guide. Interfaces built within MediaWiki use this theme by default, though different MediaWiki skins can and do over-ride this. See documentation about using OOUI in MediaWiki.
> -https://www.mediawiki.org/wiki/OOUI

위 안내에 따라 다른 테마를 만들고 적용할 수 있으면 교체하여야 하겠습니다

#### TODOs

- [x] 위키미디어 OOUI 포크
- [x] branch 생성
- [x] travis-ci로 커밋될 때마다 빌드해서 https://github.com/femiwiki/skin/tree/ooui 에 푸시되게 하기
  - [x] Github Personal access tokens 생성 (일단 제걸로 합니다 -낙엽)
  - [x] travis.org 연결
  - [x] .travis.yml 작성
- [x] 페미위키 테마 비슷하게 대강 만들기
- [ ] 페미위키 테마 의견 받으면서 열심히 만들기

**Comment by lens0021** [comment]
남은 작업은 https://github.com/femiwiki/oojs-ui/issues 으로 새 이슈를 만들어 관리하겠습니다.
