### ISSUE TITLE
RESTBase 도입

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#47]
#### 필요성

- 성능 최적화
- RESTBase가 있으면 위키편집기에서 시각편집기로 전환할 때 기존에 편집한 내용이 보존됨(현재는 버림 버튼을 눌러야 함)

#### TODOs
- [x] restbase에서 parsoid로 올바르게 접근 가능하게 설정 &rarr; [설정함](https://github.com/femiwiki/restbase/blob/2f4edd33257153b9c319849acba105da010e194f/Dockerfile#L31)
- https://github.com/femiwiki/restbase 리뷰
  - [x] 코드, 컴포즈파일 등 리뷰
  - [x] 이슈 https://github.com/femiwiki/restbase/issues/1 확인
- database 옆에 restbase도 띄우기
  - [x] femiwiki/mediawiki의 restbase branch를 merge
  - [x] femiwiki/database의 restbase branch를 merge
  - [x] travis-ci 확인 및 수정
  - [x] database 서버에서 git pull 후 restbase를 docker deploy
- `https://femiwiki.com/femiwiki.com`로 접근하면 `<RESTBASE 서버 주소>/femiwiki.com`로 리다이렉트되게 AWS ALB 설정 고치기
  - [x] 데이터베이스 서버로의 target group 생성(이름 `femiwiki-restbase`, port: 7231)
  - [x] `database+bots` 인스턴스를 `femiwiki-restbase` 타겟 그룹으로 등록
  - [x] 로드밸런서에서 위 규칙 생성(ID: `arn:aws:elasticloadbalancing:ap-northeast-1:302617221463:listener-rule/app/femiwiki-load-balancer/ebeed3504104bc38/71c0e97adaa91b48/f9b2ea19d9abc6c5`)
  - [x] mysql+memcached Security group(데이터베이스 서버)의 7231 포트 열기
- [x] https://femiwiki.com/femiwiki.com/v1/page/html/페미위키:대문 접속하여 잘 나오는지 확인
- [x] (점검 공지 띄운 후)mediawiki stack을 deploy 하기: ~~근데 안 하고 그냥 configs만 고쳐서 적용될수도 있음~~ &rarr; deploy 해야 함
- 해결할 문제
  - [x] `/srv/femiwiki.com/extensions/AWS`에 composer.lock이나 vendor 폴더가 없었으며 일단 수동으로 `composer update --no-dev` 함 &rarr; `docker run -it --rm femiwiki/mediawiki ls extensions/AWS
` 실행 시 vendor 폴더가 잘 있어서 정확한 원인은 모르겠으나 아마 기존에 있던 volume이 제대로 교체되지 않아서 생긴 일이 아닐까 추정
  - [x] 서버의 `/home/ec2-user/mediawiki/configs`의 LocalSettings.php나 secret.php를 고쳐도 콘테이너의 `/a/LocalSettings.php`나 `/a/secret.php`가 바뀌지 않음 &rarr; https://github.com/femiwiki/mediawiki/commit/b5422a7317fa66d6c1570fb5effaa7a12b362a13 로 해결
  - [x] LocalSettings.php에서 Extension:AWS를 일시적으로 주석처리 했는데 위 문제 때문에 해제를 하지 못하여 위키 내 이미지가 정상적으로 표시되지 않고 있음

#### References

- https://www.mediawiki.org/wiki/RESTBase/Installation#Proxy_requests_to_RESTBase_from_your_webserver

**Comment by simnalamburt** [comment]
고생많으셨어요

**Comment by lens0021** [comment]
> `/srv/femiwiki.com/extensions/AWS`에 composer.lock이나 vendor 폴더가 없었으며 일단 수동으로 `composer update --no-dev` 함 → `docker run -it --rm femiwiki/mediawiki ls extensions/AWS ` 실행 시 vendor 폴더가 잘 있어서 정확한 원인은 모르겠으나 아마 기존에 있던 volume이 제대로 교체되지 않아서 생긴 일이 아닐까 추정

[도커 빌드 로그](https://cloud.docker.com/u/femiwiki/repository/registry-1.docker.io/femiwiki/mediawiki/builds/20a337e5-2f0a-4c11-9521-1a17e94b64e1)에 "the requested PHP extension simplexml is missing from your system."라는 로그가 있어서 수정했습니다 &rarr; https://github.com/femiwiki/base-extensions/commit/d9a1ff1c382aa5678d032f930ada5adc90aca202
