### ISSUE TITLE
다국어 지원

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#58]
#### TODOs

- 스킨 등 확장기능의 모든 한글 리터럴 문자를 [메시지](https://www.mediawiki.org/wiki/Help:System_message)로 대체
  - [x] skin &rarr; https://github.com/femiwiki/skin/commit/794370efa55c0db566c9e85544c975e18fcb76cc
  - [x] Sanctions &rarr; https://github.com/femiwiki/Sanctions/pull/58
  - [x] UnifiedExtensionForFemiwiki
  - [x] CategoryIntersectionSearch
  - [x] FacetedCategory
- qqq.json 파일 검토
  - [x] Skin
  - [x] Sanctions
  - [x] UnifiedExtensionForFemiwiki
  - [x] CategoryIntersectionSearch
  - [x] FacetedCategory
- [x] [L10n 관련 확장기능들 설치](https://github.com/femiwiki/mediawiki/issues/266)
- [x] 스킨 푸터에 `language_urls`를 이용해 "다른 언어" 추가하기 (https://github.com/femiwiki/skin/issues/70)
- [x] `mw-pt-languages`는 항상 안 보이게 하기 &rarr; https://femiwiki.com/w/특:차이/137548
- ~~`<languages />`의 CSS 수정~~("다른 언어" 링크로 대체 가능하여 생략)
- ~~`mw-pt-translate-header`을 소도구를 통해 기본적으로 안 보게 해버리기(적어도 편집권한이 있을때 보이게 하기)~~ 필요해지면 추가합시다
- [x] [translatewiki.net 사용](https://github.com/femiwiki/femiwiki/issues/91)

#### References

- https://www.mediawiki.org/wiki/Localisation

#### 기타

- [페미위키:번역 프로젝트](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EB%B2%88%EC%97%AD_%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8)
- [주제:Utzosvcqqlpnsiny](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Utzosvcqqlpnsiny)`

**Comment by lens0021** [comment]
배포 후에 다음 문서는 필요 없으니 지워야 합니다.

- [미디어위키:Femiwiki-report-infringement-label](https://femiwiki.com/w/미디어위키:Femiwiki-report-infringement-label)
- [미디어위키:Femiwiki-report-infringement-label/en](https://femiwiki.com/w/미디어위키:Femiwiki-report-infringement-label/en)
- [미디어위키:Femiwiki-report-infringement-page](https://femiwiki.com/w/미디어위키:Femiwiki-report-infringement-page)
- [미디어위키:Femiwiki-terms-label](https://femiwiki.com/w/미디어위키:Femiwiki-terms-label)
- [미디어위키:Femiwiki-terms-label/en](https://femiwiki.com/w/미디어위키:Femiwiki-terms-label/en)
- [미디어위키:Femiwiki-terms-page](https://femiwiki.com/w/미디어위키:Femiwiki-terms-page)

**Comment by lens0021** [comment]
> 배포 후에 다음 문서는 필요 없으니 지워야 합니다.

지웠음
