### ISSUE TITLE
femiwiki-backups 버켓 정리

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#73]
다음 셋은 현재 Storage class가 Glacier인데, 가장 느린 (가격이 경제적인) 방법으로 Restore 후 적절히 이동조치합니다.

-  2018-09-24T15:00+09:00-femiwiki.com.tar.gz 
-  2018-10-07T00:04+09:00-uploaded-files.tar 
-  2018-10-07T03:32+09:00-deleted-images.tar 

Storage class가 Standard인 백업 파일들은 `mysql/`아래로 이동합니다.

나머지 Glacier인 데이터베이스 백업은 삭제합니다.

### TODOs
- [x] 기존의 "모든 파일들 Transition to Glacier after 14 days" S3 Lifecycle 규칙 삭제하기
- [x] Glacier로 넘어간 MySQL 외의 백업들 리스토어 요청하기 &rarr; 2019-04-14T16:10+0900 에 요청함
- [x] 그 외의 Glacier로 넘어간 MySQL 백업들 삭제하기
- [x] Glacier로 아직 안넘어간 MySQL 백업들 이동시키기
- [x] https://github.com/femiwiki/backupbot/issues/2 머지하기
- [x] 기존 MySQL 이외의 백업들 S3에서 S3 IA로 옮기기
- [x] 리스토어 완료된 위의 MySQL 외의 백업들 S3 IA로 옮기기
- [x] IAM 검토 및 필요한 경우 수정
  - [x] IAM 중 UploadBackup 롤의 `arn:aws:s3:::femiwiki-backups/*`을 `mysql` 디렉토리로 변경
- [x] 백업 저장을 기본적으로 S3가 아니라 S3 IA에 하도록 고치기 `--storage-class STANDARD_IA` &rarr; https://github.com/femiwiki/backupbot/commit/b2d7e9341bed2d1d140ea7b27e5b3f63f471a638
- [x] 백업봇 최신본 배포하기
  - [x] 백업봇 릴리즈 생성
  - [x] 백업봇 도커 이미지 빌드 후 도커 클라우드에 직접 푸시
  - [x] 데이버테이스서버 bots.yml 최신본 백업봇으로 변경
  - [x] 데이버테이스서버 bots.yml 변경사항 deploy &rarr; 2019-04-16 14:08경 실시함
- [x] 새 S3 Lifecycle 규칙 다시 활성화시키기: "`mysql/` 파일들 S3 IA에서 Glacier Deep Archive로 옮기기"
- [x] 4월 29일 이후 라이프사이클 잘 적용됐는지 확인하기: https://s3.console.aws.amazon.com/s3/buckets/femiwiki-backups/?region=ap-northeast-1&tab=overview

Related with https://github.com/femiwiki/backupbot/issues/2

**Comment by lens0021** [comment]
`2019-03-31T05:00+09:00.sql.gz` 부터 `2019-04-23T05:00+09:00.sql.gz`까지 Glacier Deep Archive로 바뀐 것 확인하여 닫습니다.
