### ISSUE TITLE
버전업

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#80]
아래 취약점에 영향받는 도커이미지들, AMI들 모조리 버전업하기

PHP ([CVE-2019-11034], [CVE-2019-11035])
memcached ([CVE-2019-11596])
MySQL ([CVE-2019-2566], [CVE-2019-2581], [CVE-2019-2592], [CVE-2019-2614], [CVE-2019-2627], [CVE-2019-2628], [CVE-2019-2632], [CVE-2019-2683])
imagemagick ([CVE-2019-9956], [CVE-2019-10650])
OpenSSH ([CVE-2018-20685], [CVE-2019-6109], [CVE-2019-6111])
libpng ([CVE-2019-7317])

[CVE-2019-11034]: https://nvd.nist.gov/vuln/detail/CVE-2019-11034
[CVE-2019-11035]: https://nvd.nist.gov/vuln/detail/CVE-2019-11035
[CVE-2019-11596]: https://nvd.nist.gov/vuln/detail/CVE-2019-11596
[CVE-2019-2566]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2566
[CVE-2019-2581]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2581
[CVE-2019-2592]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2592
[CVE-2019-2614]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2614
[CVE-2019-2627]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2627
[CVE-2019-2628]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2628
[CVE-2019-2632]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2632
[CVE-2019-2683]:  https://nvd.nist.gov/vuln/detail/CVE-2019-2683
[CVE-2019-9956]:  https://nvd.nist.gov/vuln/detail/CVE-2019-9956
[CVE-2019-10650]: https://nvd.nist.gov/vuln/detail/CVE-2019-10650
[CVE-2018-20685]: https://nvd.nist.gov/vuln/detail/CVE-2018-20685
[CVE-2019-6109]:  https://nvd.nist.gov/vuln/detail/CVE-2019-6109
[CVE-2019-6111]:  https://nvd.nist.gov/vuln/detail/CVE-2019-6111
[CVE-2019-7317]:  https://nvd.nist.gov/vuln/detail/CVE-2019-7317

### TODOs
- 미디어위키 버전업 https://github.com/femiwiki/mediawiki/issues/269
  - [x] 도커파일 수정
  - 태그 생성 및 이미지 빌드
    - [x] `femiwiki/base:build-2`
    - [x] `femiwiki/mediawiki:build-9`
  - [x] 배포
- [x] 미디어위키 1.32.3 버전업 &rarr; https://github.com/femiwiki/femiwiki/issues/80#issuecomment-509191593
- [x] MySQL과 Memcached
  - [x] 도커파일 수정(`mysql:8.0.16`과 `memcached:1.5.12-alpine`) &rarr; https://github.com/femiwiki/database/commit/16639c5
  - [x] 도커파일 수정(`mysql:8.0.17`과 `memcached:1.5.17-alpine`)
  - [x] 배포
- [x] Amazon Linux 2에 unattended upgrade같은거 돌고있는지 확인하기. &rarr; 특별히 없음. "55 package(s) needed for security, out of 77 available" 상태
- [x] yum-cron 설치, AMI도 다시 구워야함. &rarr; https://github.com/femiwiki/femiwiki/issues/111
- [x] ~~각 EC2에 들어가서 손으로 버전업 해주기~~ yum-cron 돈 것 확인

**Comment by lens0021** [comment]
[php 7.2.17](https://www.php.net/ChangeLog-7.php#7.2.17)에서 언급한 취약점이 패치되고 저희가 현재 사용중인 php는 아래와 같이 확인됩니다. 
```shell
$ docker run -it --rm femiwiki/base:build-0 php --version
PHP 7.2.15 (cli) (built: Feb  9 2019 02:52:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by simnalamburt** [comment]
@HanbitGaram @lens0021 두분이 협업해서 저 없이 마쳐주세용

**Comment by lens0021** [comment]
#### 할일

TBD

**Comment by lens0021** [comment]
MySQL과 Memcached 업그레이드되었습니다.
```
$ docker exec $(docker container ls -qf 'name=database') mysql --version
mysql  Ver 8.0.17 for Linux on x86_64 (MySQL Community Server - GPL)
$ docker exec $(docker container ls -qf 'name=memcached') memcached --version
memcached 1.5.17
```

**Comment by lens0021** [comment]
yum-cron을 깔아볼까요?

**Comment by simnalamburt** [comment]
네
