### ISSUE TITLE
Replace RESTBase storage; From Cassandra to MySQL

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#86]
페미위키에서 Cassandra를 구동할 여력이 되지 않아 RESTBase를 사용하지 못하고 있는 것 https://github.com/femiwiki/femiwiki/issues/82 과 관련 위키미디어 파운데이션의 Technical Advice IRC meeting에 참가하여 조언을 구해본 결과, RESTBase는 Backend storage로 Cassandra와 SQLite만을 지원하지만 이를 MySQL도 지원하도록 확장하는 일이 그다지 어렵지 않은 것으로 확인되어 이를 진행하기로 함.

#### TODOs

- [ ] PR 리뷰/머지
  - https://github.com/femiwiki/restbase-mod-table-mysql/pull/1
  - https://github.com/femiwiki/restbase/pull/1
  - https://github.com/femiwiki/docker-restbase/pull/4
- [ ] npm 패키지 publish
  - [femiwiki/restbase-mod-table-mysql](https://github.com/femiwiki/restbase-mod-table-mysql) &rarr; [`restbase-mod-table-mysql`](https://www.npmjs.com/package/restbase-mod-table-mysql)
  - [femiwiki/restbase](https://github.com/femiwiki/restbase) &rarr; [`@femiwiki/restbase`](https://www.npmjs.com/package/@femiwiki/restbase)
- [ ] docker-restbase 도커 이미지 빌드/배포
- [ ] docker-mediawiki PR 리뷰/머지: https://github.com/femiwiki/mediawiki/pull/289

#### 개발하기

```sh
git clone git@github.com:femiwiki/docker-restbase.git
# 혹은 git clone https://github.com/femiwiki/docker-restbase.git
cd docker-restbase && git checkout 0.19.3-mysql-test && cd ..
docker build --tag my-restbase docker-restbase/

git clone git@github.com:femiwiki/mediawiki.git
# 혹은 git clone https://github.com/femiwiki/mediawiki.git
cd mediawiki && git checkout mysqlrestbase && cd ..
cp mediawiki/configs/secret.php.example mediawiki/configs/secret.php
cp mediawiki/restbase_initialize.sql.example mediawiki/restbase_initialize.sql
sed -i 's=femiwiki/restbase:build-2=my-restbase=' mediawiki/development.yml

docker swarm init
docker stack deploy --prune -c mediawiki/development.yml mediawiki
```

#### 점검 시나리오
- [ ] MySQL에 새 데이터베이스와 유저 생성
- `mediawiki` EC2 Instance 에서 
  - [ ] `git pull`로 도커 컴포즈 파일 및 `LocalSettings.php` 파일 갱신
  - [ ] 새로 생성한 데이터베이스 인증 정보에 따라 `secret.php` 수정
  - [ ] `docker deploy`
- ...
- [ ] DB SG에서 카산드라 포트 삭제(https://github.com/femiwiki/infra/blob/7e6a08a/sg.tf#L58-L67)
- [ ] 깃헙에서 [femiwiki/cassandra](https://github.com/femiwiki/cassandra) 리포 삭제
- [ ] 도커 허브에서 `femiwiki/cassandra` 삭제 &rarr; https://cloud.docker.com/u/femiwiki/repository/docker/femiwiki/cassandra/settings

#### Reference

- https://wm-bot.wmflabs.org/logs/%23wikimedia-tech/20190626.txt
- http://wm-bot.wmflabs.org/browser/index.php?start=06%2F26%2F2019&end=06%2F26%2F2019&display=%23wikimedia-tech (위와 같은 내용, 뷰어 사용)

**Comment by lens0021** [comment]
PR 관련([디스코드 참고](https://discordapp.com/channels/314953743185477644/566264019409698817/593462684494856212)):

RESTBase에서 백앤드로 SQLite를 지원하는 것이 '카산드라도 지원하고 SQLite도 지원하고' 하는 개념이 아니라 '지원하기는 카산드라만 지원하는데 개발할 때 쓸 수 있게 SQLite로도 작동은 하게 만들어놨는데, 중소규모 위키에서는 써도 된다'는 개념 같습니다. 그래서 [package.json](https://github.com/wikimedia/restbase/blob/master/package.json)을 보시면 SQLite 관련 의존성은 아예 devDependencies로 되어 있습니다. 그래서 만일 MySQL 작업을 해도 PR을 넣기에는 다소 애매할 것 같습니다.

**Comment by simnalamburt** [comment]
ㅠㅠ 그럼 저희 포크를 유지하고 업스트림을 주기적으로 쫓아갑시다

**Comment by lens0021** [comment]
악 귀차나ㅠㅠㅠㅠ그래요머어쩔수없지

**Comment by lens0021** [comment]
`wikimedia/restbase` Repo를 포크하는 과정 중 기존 `femiwiki/restbase` Repo와 이름이 중복되어 논의 후 다음과 같이 변경함

- 기존 `femiwiki/restbase` &rarr; [`femiwiki/docker-restbase`](https://github.com/femiwiki/docker-restbase)
- [`wikimedia/restbase`](https://github.com/wikimedia/restbase)의 포크(신설) &rarr; [`femiwiki/restbase`](https://github.com/femiwiki/restbase)

**Comment by lens0021** [comment]
헷갈릴 수 있는 부분은 RESTBase와 스토리지 백앤드가 소통하는 부분은 [`wikimedia/restbase`](https://github.com/wikimedia/restbase)에는 별로 없고 대부분이 `restbase-mod-table-`로 시작하는 npm 패키지에 있다는 점입니다. 다음과 같은 npm 패키지가 있습니다.

- [restbase-mod-table-spec](https://www.npmjs.com/package/restbase-mod-table-spec)
- [restbase-mod-table-cassandra](https://www.npmjs.com/package/restbase-mod-table-cassandra)
- [restbase-mod-table-sqlite](https://www.npmjs.com/package/restbase-mod-table-sqlite)

각 README를 읽어보는 것이 이해에 도움이 될 듯합니다.

여하튼 2016년에 어떤 사람이 MySQL을 RESTBase의 백엔드로 사용하려던 시도를 하였어서([T147991](https://phabricator.wikimedia.org/T147991)) 이를 참고로 [`wikimedia/restbase-mod-table-sqlite`](https://github.com/wikimedia/restbase-mod-table-sqlite)를 포크하여 [`femiwiki/restbase-mod-table-mysql`](https://github.com/femiwiki/restbase-mod-table-mysql)을 만들고 있습니다. 이름 때문에 혼동이 있을까봐 따로 브랜치는 나누지 않고 마스터 브랜치에 작업하고 있습니다.

[Mocha](https://mochajs.org/) 기반의 유닛 테스트가 있어서 우선은 이를 모두 통과하는 것을 목표로 작업 중입니다. 다음 커맨드로 테스트를 해볼 수 있습니다.

```sh
git clone --depth 3 https://github.com/femiwiki/restbase-mod-table-mysql.git
cd restbase-mod-table-mysql
npm install
npm test
```

위키미디어는 RESTBase에서 패키지를 사용하기 위해서 npm에서 각 패키지를 배포중이지만, 똑같이 배포를 하기에는 무리가 있지 싶어서 `npm link`를 사용하도록 [dockerfile](https://github.com/femiwiki/docker-restbase/blob/mysql/Dockerfile)을 고쳤습니다.

도커 스택에서 데이터베이스 사용은 다음을 생각하고 있습니다.

- 개발환경 : 동일한 MySQL에 동일한 사용자로 `restbase`라는 데이터베이스를 생성하여 사용
- 실 서버 : 새 사용자와 `restbase`라는 새 데이터베이스를 생성하여 사용

**Comment by simnalamburt** [comment]
와 머시따

**Comment by lens0021** [comment]
#### 준비 과정

- [x] restbase-mod-table-mysql 개발
- [x] restbase-mod-table-mysql을 의존성으로 하는 restbase 포크 작성
- [ ] MySQL을 사용하는 도커화한 RESTBase를 `femiwiki/restbase:build-2` 태그로 배포
- [ ] MySQL RESTBase를 사용하도록 도커 컴포즈 및 `LocalSettings.php`, `secret.php` 수정한 것 머지

#### 배포
- [ ] MySQL에 새 데이터베이스와 유저 생성
- 서버에서 
  - [ ] 도커 컴포즈 및 `LocalSettings.php` Pull
  - [ ] `secret.php` 수정
- [ ] `docker deploy`

**Comment by lens0021** [comment]
Closed by https://github.com/femiwiki/femiwiki/issues/149
