### ISSUE TITLE
EC2 persistent instance retirement scheduled

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#89]
> EC2 has detected degradation of the underlying hardware hosting your Amazon EC2 instance associated with this event in the ap-northeast-1 region. Due to this degradation your instance could already be unreachable. We will stop your instance after 2019-09-16 19:00 UTC.
>
>You can find more information about maintenance events scheduled for your EC2 instances in the AWS Management Console (https://console.aws.amazon.com/ec2/v2/home?region=ap-northeast-1#Events)
>
>* What will happen to my instance?
Your instance will be stopped after the specified retirement date. You can start it again at any time after it’s stopped. Any data on local instance-store volumes will be lost when the instance is stopped or terminated.
>
>* What do I need to do?
>We recommend that you stop and start the instance which will migrate the instance to a new host. Please note that any data on your local instance-store volumes will not be preserved when you stop and start your instance. For more information about stopping and starting your instance, and what to expect when your instance is stopped, such as the effect on public, private and Elastic IP addresses associated with your instance, see Stop and Start Your Instance in the EC2 User Guide (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Stop_Start.html). However, if you do not need this instance, you can stop it at any time yourself or wait for EC2 to stop it after the retirement date.
>
>* Why is EC2 retiring my instance?
>EC2 may schedule instances for retirement in cases where there is an unrecoverable issue with the underlying hardware. For more information about scheduled retirement events please see the EC2 user guide (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-retirement.html). To avoid single points of failure within critical applications, please refer to our architecture center for more information on implementing fault-tolerant architectures: (http://aws.amazon.com/architecture)
>
>If you have any questions or concerns, you can contact the AWS Support Team on the community forums and via AWS Premium Support at: (http://aws.amazon.com/support)

### TODOs

- [x] 컴포즈 파일 이미지 버전 태그 더 올리기 &rarr; https://github.com/femiwiki/database/commit/81496e0
- [x] 일정 확정 및 공지
- [x] 웹서버 편집 등 막기 &rarr; https://github.com/femiwiki/mediawiki/blob/56bb090/configs/secret.php.example#L59
- [x] [백업봇](https://github.com/femiwiki/backupbot) 콘테이너 안에서 백업을 수행, 파일을 S3에 올림([S3 링크](https://s3.console.aws.amazon.com/s3/buckets/femiwiki-backups/mysql/?region=ap-northeast-1&tab=overview))
- [x] 인스턴스 stop
- [x] 인스턴스 start
- [x] `git pull`
- [x] 인스턴스에서 도커 스택 디플로이
- [x] 웹서버 편집 막기 해제
- [x] 공지 내리기
- [x] 이슈 해소 확인

**Comment by lens0021** [comment]
@simnalamburt 님 질문드려요 😆 

1. 디비 서버가 내부IP로 (외우기 쉬운)`172.31.11.11`을 사용하도록 지정했었는데, 이 아이피를 다시 쓰게 하면서 점검을 하려면 번거로워질 것 같습니다. `172.31.11.12`등으로 바꾸어도 될까요? 혹은 좀 걸리더라도 계속 `172.31.11.11`을 사용하도록 할까요?
2. 기존 인스턴스로 새 AMI를 만들어 인스턴스를 띄우는 방식과, Base AMI를 이용해 처음부터 시작하는 방법 중 어느 것이 나을까요?
3. MySQL 도커 이미지 버전이 증가하여(https://github.com/femiwiki/femiwiki/issues/80), 기존에 잘 써먹던 `/srv/mysql` 디렉토리를 통채로 갖다 옮기는 방법은 못 쓰는 것으로 생각됩니다. 맞을까요?
4. 혹은 그냥 단순하게 인스턴스를 stop 하였다가 start 하는 것으로 괜찮을까요? 이 경우 `/srv/mysql`는 마운트 되는 대로 유지하여도 괜찮을까요?

**Comment by simnalamburt** [comment]
1. 바꾸셔도 되고 안바꾸셔도 돼요 편하신대로 해주세요
2. 두 방법 모두 큰 상관 없는데 걍 stop했다가 켜는게 편할거같아요
3. 그 방법 왜 못쓰게되었나요?
4. 저희의경우 루트블록디바이스가 EBS여서 걍 stop했다가 도로 켜면 해결될거같아요 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-retirement.html 얘 참고

**Comment by lens0021** [comment]
앗 그 때 라이트세일 왔다갔다 했을 때, `/var/lib/mysql`를 그대로 가져다 쓸 수 있는 게 다행히 MySQL에 아직 새 버전이 나오지 않았기 때문이었지 않나요? 그런데 지금 거는 확인해보니까 8.0.13 &rarr; 8.0.17 이라 상관없을 것 같기도 하네요 😃

**Comment by simnalamburt** [comment]
@lens0021 네 이번엔 마이너버전업이라 괜찮을거같아요
