### ISSUE TITLE
소도구, 전역스크립트 등을 github에서 관리

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#90]
- [[[Mediawiki:Common.js]]](https://femiwiki.com/w/Mediawiki:Common.js)
- [[[Mediawiki:Common.css]]](https://femiwiki.com/w/Mediawiki:Common.css)
- [[[Mediawiki:Vector.js]]](https://femiwiki.com/w/Mediawiki:Vector.js)
- [[[Mediawiki:Vector.css]]](https://femiwiki.com/w/Mediawiki:Vector.css)
- [[[Mediawiki:Femiwiki.js]]](https://femiwiki.com/w/Mediawiki:Femiwiki.js)
- [[[Mediawiki:Femiwiki.css]]](https://femiwiki.com/w/Mediawiki:Femiwiki.css)
- [Gadget 이름공간의 문서들](https://femiwiki.com/w/Special:PrefixIndex/Gadget:)
- [Gadget definition 이름공간의 문서들](https://femiwiki.com/w/Special:PrefixIndex/Gadget%20definition:)

등 위키에 문서 형태로 저장되어 있는 각종 코드들을 깃헙 리포지토리에 저장하고, 커밋이 일어났을 경우 봇 권한으로 위키에 반영되도록 하는 파이프라인을 구성하면 다음 이점이 있을 것으로 생각됩니다.

- 친숙한 버전 관리
- 각자 원하는 에디터에서 편집 가능 - 현재는 온라인 [Ace] 에디터 한정
- 코딩 컨벤션의 일괄적 적용이 용이해짐
- 일반 이용자의 기여가 가능해짐
- Diff나 Blame 등이 용이해짐 - 미디어위키에도 자체적인 diff가 있지만 줄글을 비교하는 것이 목적인 등 근본적 한계가 있음, [WikiBlame]은 일부 위키에서만 지원
- [Typescript]나 [SASS]와 같이 컴파일이 필요한 언어를 간편히 채용할 수 있음
- 유닛 테스트 작성 가능

#### 기타
- 파일을 삭제할 경우에 문서도 같이 삭제하는가?
- 파일 이름을 변경할 경우 문서를 자동으로 이동 처리할 수 있는가?

#### TODOs

- [x] Create a repository &rarr; https://github.com/femiwiki/remote-gadgets/
- Prepare the bot account
  - [x] Create a bot account on FemiWiki
  - [x] Create a [bot password](https://femiwiki.com/w/Special:Botpasswords)
  - [x] Encrypt the password and add it to [our google doc](https://docs.google.com/document/d/1ImREXRftpktxXB8ZjPKQo0MCaubALCtDd1OiBh1P0lw)
  - [x] Add the password as a secret of the repository on Github
- [ ] ...

#### References

- https://phabricator.wikimedia.org/T71445
- https://phabricator.wikimedia.org/T187749

[ace]: https://ace.c9.io/
[wikiblame]: https://en.wikipedia.org/wiki/Wikipedia:WikiBlame
[sass]: https://sass-lang.com/
[typescript]: https://www.typescriptlang.org/
