### ISSUE TITLE
페미위키 개발 미디어위키 확장기능들의 번역 파이프라인 구성

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#91]
시스템 메시지들을 https://translatewiki.net 에 등록하여 자원봉사자가 이를 번역할 수 있게 하고 @translatewiki 가 자동으로 이를 커밋하도록 구성

#### TODOs

- [x] 레포별 봇 콜라보레이터 등록
- [x] 레포별 봇 콜라보레이터 등록 허가 기다리기
- [x] ~~레포별 마스터 브렌치 보호~~ 보호 삭제함, [T235938](https://phabricator.wikimedia.org/T235938) 참고
- [x] 레포별 봇 쓰기 권한 부여
-  [translatewiki repository](https://gerrit.wikimedia.org/r/#/admin/projects/translatewiki)에 추가
    - [x] 패치 작성 &rarr; https://gerrit.wikimedia.org/r/#/c/translatewiki/+/540007/
    - [x] 머지됨

#### References

- https://translatewiki.net/wiki/Setup_of_a_new_project
- https://www.mediawiki.org/wiki/Help:Extension:Translate/Group_configuration
- https://www.mediawiki.org/wiki/Help:Extension:Translate/Group_configuration_example

**Comment by lens0021** [comment]
https://phabricator.wikimedia.org/T235938

어떤 분께서 파브리케이터 태스크를 파주셨습니다(왜지..?)

**Comment by lens0021** [comment]
머지되었습니다. 디플로이됨에 따라 다음 링크를 통해 번역을 확인할 수 있습니다.

- https://translatewiki.net/w/i.php?title=Special:Translate&action=translate&filter=&group=mwgithub-categoryintersectionsearch
- https://translatewiki.net/w/i.php?title=Special:Translate&action=translate&filter=&group=mwgithub-facetedcategory
- https://translatewiki.net/w/i.php?title=Special:Translate&action=translate&filter=&group=mwgithub-femiwikiskin
- https://translatewiki.net/w/i.php?title=Special:Translate&action=translate&filter=&group=mwgithub-sanctions
- https://translatewiki.net/w/i.php?title=Special:Translate&action=translate&filter=&group=mwgithub-unifiedextensionforfemiwiki

[T235938](https://phabricator.wikimedia.org/T235938)가 닫히면 같이 닫겠습니다.
